import { IconAlertTriangle, IconArrowLeft, IconCircleCheck, IconClock, IconExternalLink, IconHistory } from "@tabler/icons-react";
import Link from "next/link";
import type { OperationalProcessDetail } from "@qoovex/types";
import { Badge } from "@qoovex/ui/components/badge";
import { buttonVariants } from "@qoovex/ui/components/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@qoovex/ui/components/card";
import { Timeline, TimelineActor, TimelineArtifactReference, TimelineContent, TimelineEntry, TimelineMarker, TimelineTransition } from "@qoovex/ui/components/timeline";
import { cn } from "@qoovex/ui/lib/utils";
import { DecisionAction, ExceptionAction, RetryStepAction } from "@features/operational-engine/ui/OperationalActions";
import { WorkspaceEmptyState, WorkspacePage, WorkspacePageHeader, WorkspaceState } from "@/views/workspace/WorkspacePrimitives";

function formatDate(value: string) { return new Intl.DateTimeFormat("it-IT", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }

export function OperationalProcessView({ process }: { process: OperationalProcessDetail }) {
  return <WorkspacePage>
    <WorkspacePageHeader title={process.title} description="Dettaglio persistente del processo, separato dall'audit tecnico e limitato ai riferimenti che puoi consultare." action={<Link className={cn(buttonVariants({ variant: "outline" }), "min-h-10 sm:min-h-8")} href="/dashboard"><IconArrowLeft />Centro operativo</Link>} />
    <div className="flex flex-wrap gap-2"><WorkspaceState label={process.status.replace(/_/g, " ")} tone={process.status === "TECHNICAL_FAILURE" ? "danger" : process.status.includes("COMPLETED") ? "good" : process.status === "BLOCKED" || process.status === "WAITING_FOR_DECISION" ? "warning" : "info"} /><Badge variant="outline">Affidabilita {process.reliability}</Badge><Badge variant="outline">Impatto {process.impact}</Badge><Badge variant="outline">Definizione v{process.definitionVersion}</Badge></div>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.25fr)_minmax(20rem,.75fr)]">
      <div className="grid content-start gap-6">
        <Card><CardHeader><CardTitle>Passaggi</CardTitle><CardDescription>Lifecycle centralizzato; gli stati non possono essere impostati liberamente dall'interfaccia.</CardDescription></CardHeader><CardContent><ol className="divide-y">{process.steps.map((step) => <li className="flex flex-col gap-3 py-4 first:pt-0 last:pb-0 sm:flex-row sm:items-center" key={step.id}><div className="flex min-w-0 flex-1 gap-3"><span className="grid size-7 shrink-0 place-items-center rounded-full border text-xs font-medium">{step.position + 1}</span><div><p className="font-medium">{step.label}</p><p className="mt-1 text-xs text-muted-foreground">{step.status.replace(/_/g, " ")} · tentativo {step.attemptCount}/{5}</p></div></div><RetryStepAction step={step} /></li>)}</ol></CardContent></Card>
        <Card id="timeline"><CardHeader><CardTitle>Timeline</CardTitle><CardDescription>Eventi prodotto append-only; audit tecnico, token e riferimenti Blob restano separati.</CardDescription></CardHeader><CardContent>{process.timeline.items.length ? <Timeline>{process.timeline.items.map((event) => <TimelineEntry key={event.id}><TimelineMarker><IconHistory className="size-3.5" /></TimelineMarker><TimelineContent><div className="flex flex-wrap items-start justify-between gap-2"><p className="font-medium">{event.title}</p><time className="text-xs text-muted-foreground" dateTime={event.occurredAt}>{formatDate(event.occurredAt)}</time></div>{event.summary ? <p className="mt-1 text-sm text-muted-foreground">{event.summary}</p> : null}<div className="mt-2 flex flex-wrap items-center gap-2"><TimelineActor>{event.actorType}{event.actorRole ? ` · ${event.actorRole}` : ""}</TimelineActor><Badge variant="outline">{event.reliability}</Badge><Badge variant="outline">{event.impact}</Badge></div><TimelineTransition from={event.previousState} to={event.nextState} />{event.artifacts.length ? <div className="mt-2 flex flex-wrap gap-2">{event.artifacts.map((artifact) => artifact.href ? <TimelineArtifactReference href={artifact.href} key={`${artifact.type}:${artifact.id}`}>{artifact.label ?? artifact.type.replace(/_/g, " ")}</TimelineArtifactReference> : null)}</div> : null}</TimelineContent></TimelineEntry>)}</Timeline> : <WorkspaceEmptyState title="Timeline vuota" description="Gli eventi visibili appariranno quando il runner acquisira il processo." />}</CardContent></Card>
      </div>
      <div className="grid content-start gap-6">
        <Card><CardHeader><CardTitle>Decisioni</CardTitle><CardDescription>Le conferme controllate riprendono lo step bloccato.</CardDescription></CardHeader><CardContent>{process.decisions.length ? <div className="grid gap-4">{process.decisions.map((decision) => <article className="rounded-lg border p-4" key={decision.id}><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0 flex-1"><p className="font-medium">{decision.question}</p>{decision.explanation ? <p className="mt-1 text-sm text-muted-foreground">{decision.explanation}</p> : null}</div><Badge variant={decision.status === "OPEN" ? "warning" : "success"}>{decision.status === "OPEN" ? "Aperta" : "Risolta"}</Badge></div><div className="mt-3"><DecisionAction decision={decision} /></div></article>)}</div> : <p className="flex items-center gap-2 text-sm text-muted-foreground"><IconCircleCheck className="size-4" />Nessuna decisione richiesta.</p>}</CardContent></Card>
        <Card><CardHeader><CardTitle>Eccezioni</CardTitle><CardDescription>Motivo, conseguenza e prossimo passo restano espliciti.</CardDescription></CardHeader><CardContent>{process.exceptions.length ? <div className="grid gap-4">{process.exceptions.map((exception) => <article className="rounded-lg border p-4" key={exception.id}><div className="flex items-start gap-2"><IconAlertTriangle className="mt-0.5 size-4 shrink-0" /><div className="min-w-0 flex-1"><p className="font-medium">{exception.title}</p><p className="mt-1 text-sm text-muted-foreground">{exception.explanation}</p><p className="mt-2 text-sm"><span className="font-medium">Prossimo passo:</span> {exception.nextStep}</p></div></div><div className="mt-3 flex items-center justify-between gap-3"><Badge variant={exception.status === "OPEN" ? "warning" : "success"}>{exception.status === "OPEN" ? exception.severity : "Risolta"}</Badge><ExceptionAction exception={exception} /></div></article>)}</div> : <p className="flex items-center gap-2 text-sm text-muted-foreground"><IconCircleCheck className="size-4" />Nessuna eccezione registrata.</p>}</CardContent></Card>
        <Card><CardHeader><CardTitle>Elementi collegati</CardTitle><CardDescription>Solo riferimenti tipizzati; nessun file, Blob key o URL firmato.</CardDescription></CardHeader><CardContent>{process.artifacts.length ? <div className="grid gap-2">{process.artifacts.map((artifact) => artifact.href ? <Link className="flex items-center justify-between rounded-lg border p-3 text-sm hover:bg-muted/50" href={artifact.href} key={`${artifact.type}:${artifact.id}`}><span>{artifact.label ?? artifact.type.replace(/_/g, " ")}</span><IconExternalLink className="size-4" /></Link> : <div className="rounded-lg border p-3 text-sm" key={`${artifact.type}:${artifact.id}`}>{artifact.label ?? artifact.type.replace(/_/g, " ")}</div>)}</div> : <p className="text-sm text-muted-foreground">Nessun riferimento disponibile.</p>}</CardContent></Card>
      </div>
    </div>
    <p className="flex items-center gap-2 text-xs text-muted-foreground"><IconClock className="size-4" />Creato {formatDate(process.createdAt)} · aggiornato {formatDate(process.updatedAt)}</p>
  </WorkspacePage>;
}
