import { getClientDisagreementConversations, getClientJobSiteDetail, getClientRequestConversations } from "@shared/server/job-site-lifecycle-service";
import { WorkspacePage, WorkspacePageHeader, WorkspacePanel, WorkspaceState } from "@/views/workspace/WorkspacePrimitives";
import { ActionButton, AttachmentForm, DisputeForm, InitialAgreementActions, PaymentDeclarationForm, PostClosureForm, ProposalForm, RecordTransitionForm, ReopeningForm, RequestForm, TimelineForm } from "@/views/job-site/JobSiteForms";
import { JobSiteSearch } from "@/views/job-site/JobSiteSearch";
import { WorkspaceTimeline } from "@/views/job-site/WorkspaceTimeline";
import { presentJobSiteStatus, presentJobSiteStepStatus, presentPostClosureRequestStatus } from "@shared/lib/product-state-presentation";
import { formatInitialEstimateFromPayload } from "@shared/lib/money";
import { buildClientJobSiteOverview } from "@shared/lib/job-site-overview";
import { clientJobSiteSectionTargets, getClientJobSiteNavigationSections, JobSiteSectionNavigation } from "@/views/job-site/JobSiteSectionNavigation";
import { InitialAgreementReview } from "@/views/job-site/InitialAgreementReview";
import { JobSiteOperationalOverview } from "@/views/job-site/JobSiteOperationalOverview";
import { closureSnapshotSchema, initialAgreementPayloadSchema } from "@shared/server/job-site-contracts";
import { createAttachmentContextReferences, JobSiteAttachmentList } from "@/views/job-site/JobSiteAttachmentLibrary";
import { PaymentRequestSummary } from "@/views/job-site/PaymentRequestSummary";
import { JobSiteDisagreementConversation, JobSiteRequestConversation } from "@/views/job-site/JobSiteRequestConversation";
import { JobSiteClosureConfirmation, JobSiteClosureSnapshotReview, JobSiteReopeningConfirmation, canCurrentUserConfirmReopening } from "@/views/job-site/JobSiteClosureReview";
import { isOpenChangeProposalDecision, isOpenDisagreementDecision, isOpenRequestDecision, JobSiteChangeProposalDecision, JobSiteDecisionCollection, JobSiteDecisionsSurface } from "@/views/job-site/job-site-decisions";

function date(value: Date | string | null | undefined) { return value ? new Intl.DateTimeFormat("it-IT", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Non indicata"; }
type ClientAttachment = Awaited<ReturnType<typeof getClientJobSiteDetail>>["attachments"][number];
const emptyAttachmentContextReferences = createAttachmentContextReferences({ requests: [], proposals: [], payments: [], disputes: [] });

function ContextualAttachments({ attachments, base }: { attachments: ClientAttachment[]; base: string }) {
  return <JobSiteAttachmentList attachments={attachments} base={base} contextReferences={emptyAttachmentContextReferences} title="File allegati" visibilityForAttachment={() => "SHARED"} />;
}
export default async function ClientJobSitePage({ params }: { params: Promise<{ jobSiteId: string }> }) {
  const { jobSiteId } = await params; const site = await getClientJobSiteDetail(jobSiteId); const [requestConversations, disagreementConversations] = site.status === "PENDING_INITIAL_CONFIRMATION" ? [[], []] : await Promise.all([getClientRequestConversations(jobSiteId), getClientDisagreementConversations(jobSiteId)]); const base = `/api/client/job-sites/${jobSiteId}`;
  const awaitingInitialConfirmation = site.status === "PENDING_INITIAL_CONFIRMATION";
  const initialAgreementAwaitingConfirmation = awaitingInitialConfirmation && site.initialAgreement?.status === "PENDING_CLIENT_CONFIRMATION";
  const pendingInitialAgreementVersion = initialAgreementAwaitingConfirmation ? site.initialAgreement?.currentVersion ?? null : null;
  const initialAgreementCorrectionsRequested = awaitingInitialConfirmation && site.initialAgreement?.status === "DRAFT" && Boolean(site.initialAgreement.currentVersion);
  const initialAccessDescription = initialAgreementCorrectionsRequested ? "L'Azienda deve pubblicare un nuovo riepilogo prima della tua conferma." : "Prima dell'attivazione Ã¨ disponibile soltanto il riepilogo da confermare.";
  const initialAccessMessage = initialAgreementCorrectionsRequested ? "Le correzioni sono state richieste. Potrai rivedere e confermare soltanto il nuovo riepilogo pubblicato dall'Azienda." : "Timeline e azioni operative saranno disponibili dopo la conferma della versione iniziale.";
  const initialAgreementSnapshot = pendingInitialAgreementVersion ? initialAgreementPayloadSchema.safeParse(pendingInitialAgreementVersion.payload) : null;
  const currentClosure = site.closures.find((closure) => ["PENDING_CLIENT_CONFIRMATION", "CLIENT_CONFIRMED"].includes(closure.status)) ?? null;
  const latestClosure = currentClosure ?? site.closures[0] ?? null;
  const closureSnapshot = latestClosure ? closureSnapshotSchema.safeParse(latestClosure.snapshot) : null;
  const attachmentContextReferences = createAttachmentContextReferences({
    requests: requestConversations.map((request) => ({ id: request.id, title: request.title })),
    proposals: site.changeProposals.map((proposal) => ({ id: proposal.id, version: proposal.currentVersion?.version })),
    payments: site.paymentRequests.map((payment) => ({ id: payment.id, reason: payment.reason })),
    disputes: disagreementConversations.map((disagreement) => ({ id: disagreement.id, title: disagreement.title })),
  });
  const isPostClosure = ["CLOSED", "ARCHIVED"].includes(site.status);
  const pendingReopeningProposal = site.reopeningProposals.find((proposal) => ["PROPOSED", "COUNTERPARTY_CONFIRMED"].includes(proposal.status)) ?? null;
  const visibleSections = getClientJobSiteNavigationSections({ hasClosure: Boolean(currentClosure), status: site.status });
  const openRequests = requestConversations.filter((request) => isOpenRequestDecision(request.status));
  const requestHistory = requestConversations.filter((request) => !isOpenRequestDecision(request.status));
  const openProposals = site.changeProposals.filter(isOpenChangeProposalDecision);
  const proposalHistory = site.changeProposals.filter((proposal) => !isOpenChangeProposalDecision(proposal));
  const openDisagreements = disagreementConversations.filter((disagreement) => isOpenDisagreementDecision(disagreement.status));
  const disagreementHistory = disagreementConversations.filter((disagreement) => !isOpenDisagreementDecision(disagreement.status));
  const canCreateRequestOrDisagreement = site.status === "ACTIVE" || site.status === "CLOSURE_PROPOSED";
  const canCreateProposal = site.status === "ACTIVE";
  const overview = buildClientJobSiteOverview({
    closureStatus: currentClosure?.status ?? null,
    details: awaitingInitialConfirmation ? [] : [
      ...(site.description ? [{ label: "Descrizione del lavoro", value: site.description }] : []),
      { label: "Stima iniziale", value: formatInitialEstimateFromPayload(site.initialAgreement?.currentVersion?.payload) },
      ...(site.estimatedCompletionAt ? [{ label: "Conclusione stimata", value: date(site.estimatedCompletionAt) }] : []),
      ...(site.closedAt ? [{ label: "Chiuso", value: date(site.closedAt) }] : []),
    ],
    disagreements: disagreementConversations,
    initialAgreementCorrectionsRequested,
    initialAgreementStatus: site.initialAgreement?.status ?? null,
    payments: site.paymentRequests,
    people: site.participants.slice(0, 3).map((person) => ({
      detail: person.publicRoleLabel ?? "Referente dell'Azienda",
      name: [person.user.firstName, person.user.lastName].filter(Boolean).join(" ") || site.organization.name,
    })),
    postClosureRequests: site.postClosureRequests,
    proposals: site.changeProposals,
    reopening: pendingReopeningProposal ? {
      canCurrentUserConfirm: canCurrentUserConfirmReopening(pendingReopeningProposal, "CLIENT"),
      reason: pendingReopeningProposal.reason,
      status: pendingReopeningProposal.status,
    } : null,
    requests: requestConversations,
    status: site.status,
    steps: site.steps,
  });
  const renderRequestDecision = (request: typeof requestConversations[number]) => <div key={request.id}><JobSiteRequestConversation actionsEndpoint={`${base}/requests/${request.id}`} conversation={request} revision={site.revision} /><ContextualAttachments attachments={site.attachments.filter((attachment) => attachment.category === "REQUEST" && attachment.sourceId === request.id)} base={base} /><div className="mb-4"><AttachmentForm client context={{ category: "REQUEST", relatedId: request.id, title: "Allega file a questa richiesta" }} endpoint={`${base}/attachments`} revision={site.revision} /></div></div>;
  const renderDisagreementDecision = (disagreement: typeof disagreementConversations[number]) => <div key={disagreement.id}><JobSiteDisagreementConversation actionsEndpoint={`${base}/disputes/${disagreement.id}`} conversation={disagreement} revision={site.revision} /><ContextualAttachments attachments={site.attachments.filter((attachment) => attachment.category === "DISPUTE" && attachment.sourceId === disagreement.id)} base={base} /><div className="mb-4"><AttachmentForm client context={{ category: "DISPUTE", relatedId: disagreement.id, title: "Allega file a questo disaccordo" }} endpoint={`${base}/attachments`} revision={site.revision} /></div></div>;
  const renderProposalDecision = (proposal: typeof site.changeProposals[number]) => <JobSiteChangeProposalDecision actionsEndpoint={`${base}/actions`} attachments={proposal.currentVersion && proposal.status !== "DRAFT" ? <div className="mt-3"><ContextualAttachments attachments={site.attachments.filter((attachment) => attachment.category === "PROPOSAL" && attachment.sourceId === proposal.id)} base={base} /><AttachmentForm client context={{ category: "PROPOSAL", relatedId: proposal.id, title: "Allega file a questa proposta" }} endpoint={`${base}/attachments`} revision={site.revision} /></div> : null} base={base} key={proposal.id} proposal={proposal} revision={site.revision} viewer="CLIENT" />;
  return <WorkspacePage><WorkspacePageHeader title={site.name} description={`${site.organization.name} Â· ${site.address ?? "Indirizzo non indicato"}`} action={<WorkspaceState state={presentJobSiteStatus(site.status)} />} /><JobSiteSectionNavigation sections={visibleSections} targets={clientJobSiteSectionTargets} />
    <section className="space-y-4" id="riepilogo"><JobSiteOperationalOverview overview={overview} /><div id="initial-agreement-review">{pendingInitialAgreementVersion && initialAgreementSnapshot?.success ? <InitialAgreementReview snapshot={initialAgreementSnapshot.data} actions={<InitialAgreementActions agreementVersionId={pendingInitialAgreementVersion.id} endpoint={`${base}/actions`} revision={site.revision} />} /> : pendingInitialAgreementVersion ? <WorkspacePanel title="Riepilogo iniziale non disponibile" description="Non è possibile mostrare il contenuto del riepilogo in attesa di conferma."><p className="text-sm text-muted-foreground">Chiedi all'Azienda di pubblicare nuovamente il riepilogo iniziale.</p></WorkspacePanel> : initialAgreementCorrectionsRequested ? <WorkspacePanel title="Correzioni richieste" description="La tua richiesta è stata inviata all'Azienda."><p className="text-sm text-muted-foreground">L'Azienda deve preparare e pubblicare un nuovo riepilogo prima della tua conferma.</p></WorkspacePanel> : null}</div></section>
    {awaitingInitialConfirmation ? <WorkspacePanel title="Accesso iniziale" description={initialAccessDescription}><p className="text-sm text-muted-foreground">{initialAccessMessage}</p></WorkspacePanel> : <>
    <section id="timeline" className="grid gap-4 lg:grid-cols-[1fr_22rem]"><WorkspacePanel title="Timeline condivisa"><WorkspaceTimeline actors={site.participants} events={site.timelineEvents} emptyState={<p className="text-sm text-muted-foreground">Nessun aggiornamento condiviso.</p>} /></WorkspacePanel><WorkspacePanel><TimelineForm client endpoint={`${base}/timeline`} revision={site.revision} /></WorkspacePanel></section>
    <section id="step"><WorkspacePanel title="Step">{site.steps.length ? <ul className="divide-y">{site.steps.map((step) => <li className="py-3" key={step.id}><div className="flex items-center justify-between"><strong>{step.title}</strong><WorkspaceState state={presentJobSiteStepStatus(step.status)} /></div>{step.status === "WORK_COMPLETED" ? <div className="mt-2 flex gap-2"><ActionButton endpoint={`${base}/actions`} body={{ action: "STEP_STATUS_TRANSITION@1", expectedRevision: site.revision, stepId: step.id, nextStatus: "CONFIRMED" }} label="Conferma" success="Step confermato." /><ActionButton endpoint={`${base}/actions`} body={{ action: "STEP_STATUS_TRANSITION@1", expectedRevision: site.revision, stepId: step.id, nextStatus: "CHANGES_REQUESTED" }} label="Richiedi modifiche" success="Modifiche richieste." /></div> : null}</li>)}</ul> : <p className="text-sm text-muted-foreground">Questo cantiere non usa step.</p>}</WorkspacePanel></section>
    <JobSiteDecisionsSurface openCount={openRequests.length + openProposals.length + openDisagreements.length}>
      <JobSiteDecisionCollection creation={canCreateRequestOrDisagreement ? <RequestForm endpoint={`${base}/requests`} revision={site.revision} /> : undefined} description="Domande operative e risposte tra Cliente e Azienda." emptyDescription="Nessuna richiesta richiede una risposta o una chiusura." id="richieste" openItems={openRequests.map(renderRequestDecision)} openTitle="Richieste aperte" secondaryItems={requestHistory.map(renderRequestDecision)} secondaryTitle="Richieste concluse" title="Richieste e risposte" />
      <JobSiteDecisionCollection creation={canCreateProposal ? <ProposalForm endpoint={`${base}/proposals`} revision={site.revision} side="CLIENT" /> : undefined} description="Variazioni alle condizioni del lavoro che una parte propone e l'altra valuta." emptyDescription="Nessuna proposta richiede una decisione." id="modifiche" openItems={openProposals.map(renderProposalDecision)} openTitle="Proposte da valutare" secondaryItems={proposalHistory.map(renderProposalDecision)} secondaryTitle="Altre proposte" title="Proposte di modifica" />
      <JobSiteDecisionCollection creation={canCreateRequestOrDisagreement ? <DisputeForm endpoint={`${base}/disputes`} revision={site.revision} /> : undefined} description="Posizioni non condivise che le parti possono discutere e chiudere. Qoovex registra il confronto, senza decidere chi ha ragione." emptyDescription="Nessun disaccordo richiede un intervento." id="disaccordi" openItems={openDisagreements.map(renderDisagreementDecision)} openTitle="Disaccordi aperti" secondaryItems={disagreementHistory.map(renderDisagreementDecision)} secondaryTitle="Disaccordi conclusi" title="Disaccordi" />
    </JobSiteDecisionsSurface>
    <section id="pagamenti"><WorkspacePanel title="Pagamenti documentati" description="Qoovex registra le dichiarazioni delle parti: non esegue, custodisce nÃ© garantisce il pagamento.">{site.paymentRequests.length ? <ul className="divide-y">{site.paymentRequests.map((payment) => <li className="py-3" key={payment.id}><PaymentRequestSummary payment={payment} viewer="CLIENT" />{payment.status === "REQUESTED" ? <PaymentDeclarationForm endpoint={`${base}/actions`} revision={site.revision} paymentRequestId={payment.id} amountMinor={payment.amountMinor.toString()} reason={payment.reason} receiptAttachments={site.attachments.filter((attachment) => attachment.category === "PAYMENT_RECEIPT" && attachment.sourceId === payment.id).map((attachment) => ({ id: attachment.id, label: attachment.originalFileName }))} /> : null}{["REQUESTED", "TRANSFER_DECLARED", "UNDER_REVIEW", "DISPUTED"].includes(payment.status) ? <div className="mt-3"><ContextualAttachments attachments={site.attachments.filter((attachment) => attachment.category === "PAYMENT_RECEIPT" && attachment.sourceId === payment.id)} base={base} /><AttachmentForm client context={{ category: "PAYMENT_RECEIPT", relatedId: payment.id, title: "Allega ricevuta di pagamento" }} endpoint={`${base}/attachments`} revision={site.revision} /></div> : null}</li>)}</ul> : <p className="text-sm text-muted-foreground">Nessuna richiesta di pagamento.</p>}</WorkspacePanel></section>
    <section id="persone"><WorkspacePanel title="Persone">{site.participants.map((person) => <div className="py-2" key={person.id}><strong>{[person.user.firstName, person.user.lastName].filter(Boolean).join(" ")}</strong><p className="text-sm text-muted-foreground">{person.publicRoleLabel ?? "Ruolo operativo non indicato"}</p></div>)}</WorkspacePanel></section>
    <section id="documenti"><WorkspacePanel title="Documenti condivisi">{site.attachments.length ? <JobSiteAttachmentList attachments={site.attachments} base={base} contextReferences={attachmentContextReferences} visibilityForAttachment={() => "SHARED"} /> : <p className="text-sm text-muted-foreground">Nessun documento condiviso.</p>}<div className="mt-6"><JobSiteSearch endpoint={`${base}/search`} /></div></WorkspacePanel></section>
    {currentClosure ? <section id="chiusura" className="grid gap-4 lg:grid-cols-2">{closureSnapshot?.success ? <JobSiteClosureSnapshotReview snapshot={closureSnapshot.data} /> : <WorkspacePanel title="Riepilogo della chiusura"><p className="text-sm text-muted-foreground">Il riepilogo della chiusura non è disponibile.</p></WorkspacePanel>}<WorkspacePanel title="Chiusura reciproca">{site.closures.length ? <div className="divide-y">{site.closures.map((closure) => <JobSiteClosureConfirmation actionsEndpoint={`${base}/actions`} closure={closure} key={closure.id} revision={site.revision} viewer="CLIENT" />)}</div> : <p className="text-sm text-muted-foreground">Nessuna chiusura proposta.</p>}</WorkspacePanel></section> : null}
    {isPostClosure ? <><section id="archivio" className="grid gap-4 lg:grid-cols-2">{closureSnapshot?.success ? <JobSiteClosureSnapshotReview snapshot={closureSnapshot.data} /> : <WorkspacePanel title="Riepilogo della chiusura"><p className="text-sm text-muted-foreground">Il riepilogo registrato della chiusura non è disponibile.</p></WorkspacePanel>}<WorkspacePanel title="Archivio del cantiere" description={site.status === "CLOSED" ? "Il lavoro è chiuso. Qui trovi il riepilogo registrato e le funzioni disponibili dopo la chiusura." : "Il lavoro è archiviato. Qui restano disponibili il riepilogo registrato e lo storico della chiusura."}>{site.closures.length ? <div className="divide-y">{site.closures.map((closure) => <JobSiteClosureConfirmation actionsEndpoint={`${base}/actions`} closure={closure} key={closure.id} revision={site.revision} viewer="CLIENT" />)}</div> : <p className="text-sm text-muted-foreground">Nessuna chiusura registrata.</p>}<div className="mt-4"><ActionButton endpoint={`${base}/actions`} body={{ action: "JOB_SITE_EXPORT_CREATE@1", expectedRevision: site.revision, audience: "CLIENT" }} label="Prepara archivio cliente" success="Preparazione avviata." /></div></WorkspacePanel></section><section aria-label="Attività dopo la chiusura" className="grid gap-4 lg:grid-cols-2"><WorkspacePanel title="Richieste dopo la chiusura" description="Queste richieste riguardano il lavoro già chiuso.">{site.postClosureRequests.map((request) => <div className="border-b py-3" key={request.id}><div className="flex items-center justify-between"><strong>{request.title}</strong><WorkspaceState state={presentPostClosureRequestStatus(request.status)} /></div>{["OPEN", "IN_DISCUSSION"].includes(request.status) ? <RecordTransitionForm endpoint={`${base}/post-closure/${request.id}`} revision={site.revision} actions={[{ value: "RESPOND", label: "Rispondi" }, { value: "RESOLVE", label: "Risolvi" }, { value: "WITHDRAW", label: "Ritira" }, { value: "CLOSE_WITHOUT_AGREEMENT", label: "Chiudi senza accordo" }]} /> : null}</div>)}<PostClosureForm endpoint={`${base}/post-closure`} revision={site.revision} /></WorkspacePanel><WorkspacePanel title="Riapertura del cantiere" description="La riapertura riporta il cantiere alle sezioni operative solo dopo la conferma di entrambe le parti.">{site.reopeningProposals.length ? <div className="divide-y">{site.reopeningProposals.map((proposal) => <JobSiteReopeningConfirmation actionsEndpoint={`${base}/actions`} key={proposal.id} proposal={proposal} revision={site.revision} viewer="CLIENT" />)}</div> : <p className="text-sm text-muted-foreground">Nessuna proposta di riapertura.</p>}{!pendingReopeningProposal ? <div className="mt-5 border-t pt-5"><ReopeningForm endpoint={`${base}/reopening`} revision={site.revision} /></div> : null}</WorkspacePanel></section></> : null}
    </>}
  </WorkspacePage>;
}
