import { IconAlertTriangle, IconCircleCheck, IconFile, IconRobotOff, IconUserCheck } from "@tabler/icons-react";
import { Badge } from "@qoovex/ui/components/badge";
import { Button } from "@qoovex/ui/components/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@qoovex/ui/components/card";
import { Empty, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "@qoovex/ui/components/empty";
import { SearchField, SearchResults } from "@qoovex/ui/components/search-field";
import { Timeline, TimelineActor, TimelineArtifactReference, TimelineContent, TimelineDateSeparator, TimelineEntry, TimelineMarker, TimelineTransition } from "@qoovex/ui/components/timeline";
import { WorkQueueItem, WorkQueueItemActions, WorkQueueItemContent } from "@qoovex/ui/components/work-queue-item";

export default function OperationalControlProofPage() {
  return (
    <main className="mx-auto grid w-full max-w-6xl gap-8 p-4 py-8 sm:p-8">
      <header className="grid gap-2"><Badge className="w-fit" variant="outline">Sirio proof · Fase 4</Badge><h1 className="text-2xl font-semibold tracking-tight">Controllo operativo verificabile</h1><p className="max-w-3xl text-muted-foreground">Primitive generiche per ricerca, coda e timeline. Il linguaggio visivo, i token e la motion restano quelli canonici.</p></header>
      <section className="grid gap-4"><h2 className="text-lg font-medium">Ricerca multi-tipo</h2><SearchField aria-label="Cerca nel catalogo dimostrativo" defaultValue="DUVRI" /><SearchResults><Card><CardHeader><CardTitle>DUVRI · Cantiere Aurora</CardTitle><CardDescription>Documento · da verificare · scadenza 31 luglio</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-2"><Badge>Documento</Badge><Badge variant="outline">Corrispondenza esatta</Badge></CardContent></Card><Empty><EmptyHeader><EmptyMedia variant="icon"><IconRobotOff /></EmptyMedia><EmptyTitle>Nessun contenuto file indicizzato</EmptyTitle><EmptyDescription>La ricerca usa soltanto metadati autorizzati.</EmptyDescription></EmptyHeader></Empty></SearchResults></section>
      <section className="grid gap-4"><h2 className="text-lg font-medium">Coda operativa</h2><WorkQueueItem priority="blocking"><WorkQueueItemContent><div className="flex flex-wrap gap-2"><Badge variant="destructive">Bloccante</Badge><Badge variant="outline">Condivisione</Badge></div><h3 className="font-medium">Pacchetto ingresso subappaltatore</h3><p className="text-sm text-muted-foreground">Un documento è scaduto e uno richiede verifica prima dell’approvazione.</p></WorkQueueItemContent><WorkQueueItemActions><Button variant="outline">Apri processo</Button><Button>Rivedi</Button></WorkQueueItemActions></WorkQueueItem><WorkQueueItem priority="attention"><WorkQueueItemContent><Badge variant="outline">Da decidere</Badge><h3 className="font-medium">Conferma destinatario e scadenza</h3><p className="text-sm text-muted-foreground">Nessuna pubblicazione automatica.</p></WorkQueueItemContent><WorkQueueItemActions><Button>Decidi</Button></WorkQueueItemActions></WorkQueueItem></section>
      <section className="grid gap-4"><h2 className="text-lg font-medium">Timeline lunga</h2><Timeline><TimelineDateSeparator>Oggi</TimelineDateSeparator><TimelineEntry><TimelineMarker><IconFile className="size-3.5" /></TimelineMarker><TimelineContent><div className="flex flex-wrap items-start justify-between gap-2"><strong>Revisione preparata</strong><time className="text-xs text-muted-foreground">10:42</time></div><p className="mt-1 text-sm text-muted-foreground">Manifest immutabile creato con 5 riferimenti autorizzati.</p><TimelineActor>Sistema · affidabilità verificata</TimelineActor><div className="mt-2"><TimelineArtifactReference href="#">Pacchetto ingresso</TimelineArtifactReference></div><TimelineTransition from="PREPARING" to="READY_FOR_REVIEW" /></TimelineContent></TimelineEntry><TimelineEntry><TimelineMarker><IconUserCheck className="size-3.5" /></TimelineMarker><TimelineContent><strong>Decisione richiesta</strong><p className="mt-1 text-sm text-muted-foreground">L’utente deve controllare inclusi, esclusi, scadenza e download.</p><TimelineActor>Utente autorizzato</TimelineActor></TimelineContent></TimelineEntry><TimelineEntry><TimelineMarker><IconAlertTriangle className="size-3.5" /></TimelineMarker><TimelineContent><strong>Correzione append-only</strong><p className="mt-1 text-sm text-muted-foreground">La correzione aggiunge un evento senza riscrivere quello storico.</p><TimelineActor>Supporto · visibilità controllata</TimelineActor></TimelineContent></TimelineEntry><TimelineEntry><TimelineMarker><IconCircleCheck className="size-3.5" /></TimelineMarker><TimelineContent><strong>Risultato confermato</strong><p className="mt-1 text-sm text-muted-foreground">Il token sarà restituito una sola volta al momento della conferma.</p></TimelineContent></TimelineEntry></Timeline></section>
    </main>
  );
}
