-- Preserve identity and security data while removing the retired product domain.
DROP TABLE IF EXISTS "ShoppingListItem" CASCADE;
DROP TABLE IF EXISTS "ShoppingList" CASCADE;
DROP TABLE IF EXISTS "WorkTask" CASCADE;
DROP TABLE IF EXISTS "WorkPlanMember" CASCADE;
DROP TABLE IF EXISTS "WorkPlan" CASCADE;
DROP TABLE IF EXISTS "MenuItem" CASCADE;
DROP TABLE IF EXISTS "Menu" CASCADE;
DROP TABLE IF EXISTS "IngredientReview" CASCADE;
DROP TABLE IF EXISTS "RecipeIngredient" CASCADE;
DROP TABLE IF EXISTS "Ingredient" CASCADE;
DROP TABLE IF EXISTS "Recipe" CASCADE;
DROP TABLE IF EXISTS "Notification" CASCADE;
DROP TABLE IF EXISTS "RecentSearch" CASCADE;

ALTER TABLE "User" DROP COLUMN IF EXISTS "plan";

DROP TYPE IF EXISTS "Plan";
DROP TYPE IF EXISTS "RecipeCategory";
DROP TYPE IF EXISTS "RecipeStatus";
DROP TYPE IF EXISTS "IngredientVerificationStatus";
DROP TYPE IF EXISTS "IngredientSource";
