CREATE TYPE "DocumentCategoryKey" AS ENUM (
  'COMPANY_IDENTITY_REGISTRATIONS',
  'COMPANY_REGULARITY_QUALIFICATIONS',
  'COMPANY_SAFETY',
  'COMPANY_INSURANCE',
  'COMPANY_ROLES_ORGANIZATION',
  'WORKER_IDENTITY_ACCESS',
  'WORKER_TRAINING_QUALIFICATIONS',
  'WORKER_FITNESS_JUDGMENT',
  'WORKER_PPE_DELIVERIES',
  'WORKER_ROLES_ASSIGNMENTS',
  'WORKER_RESTRICTED_ADMINISTRATION',
  'SITE_START_AUTHORIZATIONS',
  'SITE_SAFETY_COORDINATION',
  'SITE_COMPANIES_SUBCONTRACTS',
  'SITE_WORKERS_ACCESS',
  'SITE_EQUIPMENT_SYSTEMS',
  'SITE_REPORTS_INSPECTIONS',
  'SITE_CLOSURE_HANDOVER',
  'UNCLASSIFIED'
);

CREATE TYPE "DocumentSensitivity" AS ENUM ('STANDARD', 'RESTRICTED', 'HEALTH_JUDGMENT');

ALTER TABLE "DocumentType"
  ADD COLUMN "categoryKey" "DocumentCategoryKey" NOT NULL DEFAULT 'UNCLASSIFIED',
  ADD COLUMN "sensitivity" "DocumentSensitivity" NOT NULL DEFAULT 'STANDARD';

CREATE INDEX "DocumentType_org_category_archived_idx"
  ON "DocumentType"("organizationId", "categoryKey", "archivedAt");

-- I tipi esistenti restano intenzionalmente UNCLASSIFIED: nessuna inferenza dal nome.
