export const transactionalEmailTokens = {
  background: "#000000",
  card: "#242424",
  cardBorder: "#424242",
  foreground: "#ffffff",
  muted: "#b8b8b8",
  secondary: "#737373",
  inset: "#1a1a1a",
  buttonBackground: "#ffffff",
  buttonText: "#000000",
  buttonOutlineBorder: "#424242",
  buttonOutlineText: "#ffffff",
  severityInfo: "#b8b8b8",
  severityAttention: "#9ca3af",
  severityWarning: "#f5c542",
  fontSans: "'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
  fontMono: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
  radius: "8px",
  radiusLg: "12px",
  maxWidth: "560px",
} as const;
