import "server-only";
import { db } from "@qoovex/db";
import type { DataInventoryResponse, DataRecordCount } from "@qoovex/types";
import { requireDataControlAccess } from "./data-control-access";

async function archived(model: { count(args: { where: Record<string, unknown> }): Promise<number> }, organizationId: string): Promise<DataRecordCount> {
  const [total, active] = await Promise.all([model.count({ where: { organizationId } }), model.count({ where: { organizationId, archivedAt: null } })]);
  return { total, active, archived: total - active };
}
async function total(model: { count(args: { where: Record<string, unknown> }): Promise<number> }, organizationId: string): Promise<DataRecordCount> { return { total: await model.count({ where: { organizationId } }) }; }

export async function buildDataInventoryForOrganization(organizationId: string, now = new Date()): Promise<DataInventoryResponse> {
  const members = await db.user.findMany({ where: { organizationMembership: { is: { organizationId } } }, select: { id: true, email: true } });
  const userIds = members.map((value) => value.id); const emails = members.map((value) => value.email);
  const [workers, jobSites, documents, documentVersions, evidence, evidenceRevisions, documentJobSiteLinks, notifications, auditEvents, workerUserLinks, jobSiteUserAssignments, jobSiteWorkerAssignments, memberships, invitations, dataControlJobs, supportSessions, supportEvents, authProviders, authSessions, authCredentials, authCodes, mfaRecoveryRequests, authDevices, mfaBackupCodes, securityAuditEvents, authRateLimits] = await Promise.all([
    archived(db.worker, organizationId), archived(db.jobSite, organizationId), archived(db.document, organizationId), archived(db.documentVersion, organizationId), archived(db.evidence, organizationId), total(db.evidenceRevision, organizationId), total(db.documentJobSiteLink, organizationId), total(db.notification, organizationId), total(db.productAuditEvent, organizationId), archived(db.workerUserLink, organizationId), archived(db.jobSiteUserAssignment, organizationId), archived(db.jobSiteWorkerAssignment, organizationId), total(db.organizationMembership, organizationId), total(db.organizationInvitation, organizationId), total(db.dataControlJob, organizationId), total(db.supportSession, organizationId), total(db.supportAuditEvent, organizationId), db.account.count({ where: { userId: { in: userIds } } }).then((value) => ({ total: value })), db.session.count({ where: { userId: { in: userIds } } }).then((value) => ({ total: value })), db.userCredential.count({ where: { userId: { in: userIds } } }).then((value) => ({ total: value })), db.authCode.count({ where: { OR: [{ userId: { in: userIds } }, { email: { in: emails } }] } }).then((value) => ({ total: value })), db.mfaRecoveryRequest.count({ where: { OR: [{ organizationId }, { userId: { in: userIds } }] } }).then((value) => ({ total: value })), db.authDevice.count({ where: { userId: { in: userIds } } }).then((value) => ({ total: value })), db.mfaBackupCode.count({ where: { userId: { in: userIds } } }).then((value) => ({ total: value })), db.securityAuditEvent.count({ where: { OR: [{ userId: { in: userIds } }, { email: { in: emails } }] } }).then((value) => ({ total: value })), db.authRateLimit.count({ where: { userId: { in: userIds } } }).then((value) => ({ total: value })),
  ]);
  return { generatedAt: now.toISOString(), counts: { workers, jobSites, documents, documentVersions, evidence, evidenceRevisions, documentJobSiteLinks, notifications, auditEvents, workerUserLinks, jobSiteUserAssignments, jobSiteWorkerAssignments, memberProfiles: { total: members.length }, memberships, invitations, dataControlJobs, supportSessions, supportEvents, authProviders, authSessions, authCredentials, authCodes, mfaRecoveryRequests, authDevices, mfaBackupCodes, securityAuditEvents, authRateLimits } };
}
export async function getDataInventory() { const { organizationId } = await requireDataControlAccess(); return buildDataInventoryForOrganization(organizationId); }
