import "server-only";

import { db } from "@qoovex/db";
import type { DataInventoryResponse, DataRecordCount } from "@qoovex/types";
import { requireDataControlAccess } from "./data-control-access";

async function archivedCount(model: { count: (args: { where: Record<string, unknown> }) => Promise<number> }, organizationId: string): Promise<DataRecordCount> {
  const [total, active] = await Promise.all([
    model.count({ where: { organizationId } }),
    model.count({ where: { organizationId, archivedAt: null } }),
  ]);
  return { total, active, archived: total - active };
}

async function totalCount(model: { count: (args: { where: Record<string, unknown> }) => Promise<number> }, organizationId: string): Promise<DataRecordCount> {
  return { total: await model.count({ where: { organizationId } }) };
}

export async function buildDataInventoryForOrganization(organizationId: string, now = new Date()): Promise<DataInventoryResponse> {
  const memberIdentities = await db.user.findMany({
    where: { organizationMembership: { is: { organizationId } } },
    select: { id: true, email: true },
  });
  const memberUserIds = memberIdentities.map((member) => member.id);
  const memberEmails = memberIdentities.map((member) => member.email);
  const [
    workers,
    jobSites,
    documentTypes,
    documentRequirements,
    documents,
    documentVersions,
    deadlines,
    calendarEvents,
    checklists,
    checklistItems,
    evidence,
    documentPackages,
    documentPackageItems,
    shareLinksActive,
    shareLinksExpired,
    shareLinksRevoked,
    notificationsUnread,
    notificationsRead,
    notificationsDismissed,
    notificationPreferences,
    emailDeliveries,
    auditEvents,
    workerUserLinks,
    jobSiteUserAssignments,
    jobSiteWorkerAssignments,
    memberships,
    invitations,
    dataControlJobs,
    supportSessions,
    supportEvents,
    authProviders,
    authSessions,
    authCredentials,
    authCodes,
    mfaRecoveryRequests,
    authDevices,
    mfaBackupCodes,
    securityAuditEvents,
    authRateLimits,
    operationalProcesses,
    operationalSteps,
    operationalEvents,
    operationalDecisions,
    operationalExceptions,
    operationalArtifactReferences,
    operationalEventArtifactReferences,
    operationalRuleSnapshots,
    operationalEffectReceipts,
    documentJobSiteLinks,
    evidenceRevisions,
    documentPackageRevisions,
    operationalRequests,
    contextMessages,
    contextTimelineEvents,
    documentSourcePolicies,
    documentSourceChecks,
    documentAcquisitions,
    documentPackageShareProposals,
  ] = await Promise.all([
    archivedCount(db.worker, organizationId),
    archivedCount(db.jobSite, organizationId),
    archivedCount(db.documentType, organizationId),
    archivedCount(db.documentRequirement, organizationId),
    archivedCount(db.document, organizationId),
    archivedCount(db.documentVersion, organizationId),
    archivedCount(db.deadline, organizationId),
    archivedCount(db.calendarEvent, organizationId),
    archivedCount(db.checklist, organizationId),
    db.checklistItem.groupBy({
      by: ["status"],
      where: { organizationId },
      _count: { _all: true },
    }).then((groups) => {
      const total = groups.reduce((sum, group) => sum + group._count._all, 0);
      const archived = groups.find((group) => group.status === "ARCHIVED")?._count._all ?? 0;
      return { total, active: total - archived, archived };
    }),
    archivedCount(db.evidence, organizationId),
    archivedCount(db.documentPackage, organizationId),
    totalCount(db.documentPackageItem, organizationId),
    db.shareLink.count({ where: { organizationId, revokedAt: null, OR: [{ expiresAt: null }, { expiresAt: { gt: now } }] } }),
    db.shareLink.count({ where: { organizationId, revokedAt: null, expiresAt: { lte: now } } }),
    db.shareLink.count({ where: { organizationId, revokedAt: { not: null } } }),
    db.notification.count({ where: { organizationId, readAt: null, dismissedAt: null } }),
    db.notification.count({ where: { organizationId, readAt: { not: null }, dismissedAt: null } }),
    db.notification.count({ where: { organizationId, dismissedAt: { not: null } } }),
    totalCount(db.notificationPreference, organizationId),
    totalCount(db.notificationEmailDelivery, organizationId),
    totalCount(db.productAuditEvent, organizationId),
    archivedCount(db.workerUserLink, organizationId),
    archivedCount(db.jobSiteUserAssignment, organizationId),
    archivedCount(db.jobSiteWorkerAssignment, organizationId),
    db.organizationMembership.count({ where: { organizationId } }).then((total) => ({ total })),
    db.organizationInvitation.count({ where: { organizationId } }).then((total) => ({ total })),
    db.dataControlJob.count({ where: { organizationId } }).then((total) => ({ total })),
    db.supportSession.count({ where: { organizationId } }).then((total) => ({ total })),
    db.supportAuditEvent.count({ where: { organizationId } }).then((total) => ({ total })),
    db.account.count({ where: { userId: { in: memberUserIds } } }).then((total) => ({ total })),
    Promise.all([
      db.session.count({ where: { userId: { in: memberUserIds } } }),
      db.session.count({ where: { userId: { in: memberUserIds }, expires: { gt: now } } }),
    ]).then(([total, active]) => ({ total, active })),
    db.userCredential.count({ where: { userId: { in: memberUserIds } } }).then((total) => ({ total })),
    Promise.all([
      db.authCode.count({ where: { OR: [{ userId: { in: memberUserIds } }, { email: { in: memberEmails } }] } }),
      db.authCode.count({ where: { OR: [{ userId: { in: memberUserIds } }, { email: { in: memberEmails } }], consumedAt: null, expiresAt: { gt: now } } }),
    ]).then(([total, active]) => ({ total, active })),
    db.mfaRecoveryRequest.count({ where: { OR: [{ organizationId }, { userId: { in: memberUserIds } }] } }).then((total) => ({ total })),
    db.authDevice.count({ where: { userId: { in: memberUserIds } } }).then((total) => ({ total })),
    Promise.all([
      db.mfaBackupCode.count({ where: { userId: { in: memberUserIds } } }),
      db.mfaBackupCode.count({ where: { userId: { in: memberUserIds }, usedAt: null } }),
    ]).then(([total, active]) => ({ total, active })),
    db.securityAuditEvent.count({ where: { OR: [{ userId: { in: memberUserIds } }, { email: { in: memberEmails } }] } }).then((total) => ({ total })),
    db.authRateLimit.count({ where: { userId: { in: memberUserIds } } }).then((total) => ({ total })),
    totalCount(db.operationalProcess, organizationId),
    totalCount(db.operationalStep, organizationId),
    totalCount(db.operationalEvent, organizationId),
    totalCount(db.operationalDecision, organizationId),
    totalCount(db.operationalException, organizationId),
    totalCount(db.operationalArtifactReference, organizationId),
    totalCount(db.operationalEventArtifactReference, organizationId),
    totalCount(db.operationalRuleSnapshot, organizationId),
    totalCount(db.operationalEffectReceipt, organizationId),
    totalCount(db.documentJobSiteLink, organizationId),
    totalCount(db.evidenceRevision, organizationId),
    totalCount(db.documentPackageRevision, organizationId),
    totalCount(db.operationalRequest, organizationId),
    totalCount(db.contextMessage, organizationId),
    totalCount(db.contextTimelineEvent, organizationId),
    archivedCount(db.documentSourcePolicy, organizationId),
    totalCount(db.documentSourceCheck, organizationId),
    totalCount(db.documentAcquisition, organizationId),
    totalCount(db.documentPackageShareProposal, organizationId),
  ]);

  return {
    generatedAt: now.toISOString(),
    counts: {
      workers,
      jobSites,
      documentTypes,
      documentRequirements,
      documents,
      documentVersions,
      deadlines,
      calendarEvents,
      checklists,
      checklistItems,
      evidence,
      documentPackages,
      documentPackageItems,
      shareLinks: { total: shareLinksActive + shareLinksExpired + shareLinksRevoked, active: shareLinksActive, expired: shareLinksExpired, revoked: shareLinksRevoked },
      notifications: { total: notificationsUnread + notificationsRead + notificationsDismissed, unread: notificationsUnread, read: notificationsRead, dismissed: notificationsDismissed },
      notificationPreferences,
      emailDeliveries,
      auditEvents,
      workerUserLinks,
      jobSiteUserAssignments,
      jobSiteWorkerAssignments,
      memberProfiles: { total: memberIdentities.length },
      memberships,
      invitations,
      dataControlJobs,
      supportSessions,
      supportEvents,
      authProviders,
      authSessions,
      authCredentials,
      authCodes,
      mfaRecoveryRequests,
      authDevices,
      mfaBackupCodes,
      securityAuditEvents,
      authRateLimits,
      operationalProcesses,
      operationalSteps,
      operationalEvents,
      operationalDecisions,
      operationalExceptions,
      operationalArtifactReferences,
      operationalEventArtifactReferences,
      operationalRuleSnapshots,
      operationalEffectReceipts,
      documentJobSiteLinks,
      evidenceRevisions,
      documentPackageRevisions,
      operationalRequests,
      contextMessages,
      contextTimelineEvents,
      documentSourcePolicies,
      documentSourceChecks,
      documentAcquisitions,
      documentPackageShareProposals,
    },
  };
}

export async function getDataInventory() {
  const { organizationId } = await requireDataControlAccess();
  return await buildDataInventoryForOrganization(organizationId);
}
