import "server-only";

export const VNEXT_ACTION_DEFINITIONS = [
  "JOB_SITE_CREATE@1", "CLIENT_INVITATION_CREATE@1", "CLIENT_INVITATION_REVOKE@1", "CLIENT_PARTICIPATION_ACTIVATE@1", "CLIENT_PARTICIPATION_SUSPEND@1", "CLIENT_PARTICIPATION_REACTIVATE@1", "CLIENT_PARTICIPATION_REVOKE@1",
  "INITIAL_AGREEMENT_PUBLISH@1", "INITIAL_AGREEMENT_CONFIRM@1", "TIMELINE_APPEND@1", "STEP_CREATE@1", "STEP_STATUS_TRANSITION@1", "JOB_SITE_RESPONSIBLE_CHANGE@1",
  "AUTHORITY_GRANT@1", "AUTHORITY_REVOKE@1",
  "JOB_SITE_REQUEST_CREATE@1", "JOB_SITE_REQUEST_RESPOND@1", "JOB_SITE_REQUEST_RESOLVE@1", "JOB_SITE_REQUEST_WITHDRAW@1",
  "CHANGE_PROPOSAL_CREATE@1", "CHANGE_PROPOSAL_APPLY@1", "CHANGE_PROPOSAL_COUNTER@1", "CHANGE_PROPOSAL_WITHDRAW@1",
  "PAYMENT_REQUEST_CREATE@1", "PAYMENT_TRANSFER_DECLARE@1", "PAYMENT_RECEIPT_CONFIRM@1",
  "DISPUTE_CREATE@1", "DISPUTE_PRESERVATION_CREATE@1", "DISPUTE_RESPOND@1", "DISPUTE_AGREE@1", "DISPUTE_WITHDRAW@1", "DISPUTE_CLOSE_WITHOUT_AGREEMENT@1",
  "POST_CLOSURE_REQUEST_CREATE@1", "POST_CLOSURE_REQUEST_RESPOND@1", "POST_CLOSURE_REQUEST_RESOLVE@1", "POST_CLOSURE_REQUEST_WITHDRAW@1", "POST_CLOSURE_REQUEST_CLOSE_WITHOUT_AGREEMENT@1",
  "CLOSURE_PROPOSE@1", "JOB_SITE_CLOSE@1", "REOPENING_PROPOSE@1", "JOB_SITE_REOPEN@1", "JOB_SITE_EXPORT_CREATE@1", "JOB_SITE_ARCHIVE@1", "ATTACHMENT_UPLOAD@1", "ATTACHMENT_FINALIZE@1",
] as const;

export type VNextActionDefinition = (typeof VNEXT_ACTION_DEFINITIONS)[number];

export const VNEXT_PROCESS_DEFINITIONS = {
  "CLIENT_INVITATION@1": ["SEND_INVITATION", "WAIT_FOR_ACCEPTANCE"],
  "JOB_SITE_INITIAL_CONFIRMATION@1": ["PUBLISH_AGREEMENT", "WAIT_FOR_CLIENT_CONFIRMATION", "ACTIVATE_JOB_SITE"],
  "CHANGE_NEGOTIATION@1": ["PUBLISH_VERSION", "WAIT_FOR_COUNTERPART", "APPLY_ACCEPTED_EFFECTS"],
  "PAYMENT_REQUEST@1": ["PUBLISH_REQUEST", "WAIT_FOR_TRANSFER", "WAIT_FOR_REVIEW"],
  "JOB_SITE_CLOSURE@1": ["BUILD_SNAPSHOT", "WAIT_FOR_CLIENT", "WAIT_FOR_ORGANIZATION", "CLOSE_JOB_SITE"],
  "JOB_SITE_EXPORT@1": ["BUILD_MANIFEST", "STREAM_ARCHIVE", "ISSUE_ACCESS_LINK"],
  "POST_CLOSURE_REQUEST@1": ["PUBLISH_REQUEST", "WAIT_FOR_RESPONSE"],
  "JOB_SITE_REOPENING@1": ["PUBLISH_PROPOSAL", "WAIT_FOR_CONSENTS", "REOPEN_JOB_SITE"],
} as const;

export type VNextProcessDefinition = keyof typeof VNEXT_PROCESS_DEFINITIONS;
type CapabilityStatus = "ACTIVE" | "INTERNAL_ONLY";
type CapabilityAudience = "CONTEXT" | "ORGANIZATION" | "CLIENT" | "SHARED_AUTHENTICATED" | "INTERNAL";
type ProductCapability = { key: string; audience: CapabilityAudience; navigationSource: string | null; route: string | null; api: string; readPermission: string | null; mutationPermission: string | null; service: string; mutation: string | null; status: CapabilityStatus; testIds: readonly string[] };
const c = (value: ProductCapability) => value;

export const PRODUCT_CAPABILITY_MANIFEST = [
  c({ key: "contexts", audience: "CONTEXT", navigationSource: "workspace-root", route: "/contexts", api: "/api/contexts", readPermission: null, mutationPermission: null, service: "getContextHub", mutation: null, status: "ACTIVE", testIds: ["context-hub"] }),
  c({ key: "notification-preferences", audience: "CONTEXT", navigationSource: "contexts", route: "/contexts/notifications", api: "/api/contexts/notification-preferences", readPermission: null, mutationPermission: "user-scoped", service: "vnext-notification-preference-service", mutation: "preference-upsert", status: "ACTIVE", testIds: ["notification-isolation"] }),
  c({ key: "org-members", audience: "ORGANIZATION", navigationSource: "org-navigation", route: "/org/[organizationId]/people", api: "/api/org/[organizationId]/members", readPermission: "members:read", mutationPermission: "members:manage", service: "vnext-organization-member-service", mutation: "organization-member-management", status: "ACTIVE", testIds: ["organization-members"] }),
  c({ key: "org-payment-profile", audience: "ORGANIZATION", navigationSource: "org-navigation", route: "/org/[organizationId]/payment-profile", api: "/api/org/[organizationId]/payment-profile", readPermission: "jobSite:payments:view", mutationPermission: "MFA+jobSite:payments:profile", service: "vnext-payment-profile-service", mutation: "payment-profile-version", status: "ACTIVE", testIds: ["iban-encryption", "mfa-payment-profile"] }),
  c({ key: "org-job-sites", audience: "ORGANIZATION", navigationSource: "org-navigation", route: "/org/[organizationId]/job-sites", api: "/api/org/[organizationId]/job-sites", readPermission: "jobSites:read", mutationPermission: "jobSites:create", service: "vnext-job-site-service", mutation: "JOB_SITE_CREATE@1", status: "ACTIVE", testIds: ["organization-job-sites"] }),
  c({ key: "org-job-site-detail", audience: "ORGANIZATION", navigationSource: "org-job-sites", route: "/org/[organizationId]/job-sites/[jobSiteId]", api: "/api/org/[organizationId]/job-sites/[jobSiteId]", readPermission: "jobSite:view", mutationPermission: null, service: "vnext-job-site-service", mutation: null, status: "ACTIVE", testIds: ["organization-job-site-detail"] }),
  c({ key: "org-actions", audience: "ORGANIZATION", navigationSource: "org-job-site-detail", route: "/org/[organizationId]/job-sites/[jobSiteId]", api: "/api/org/[organizationId]/job-sites/[jobSiteId]/actions", readPermission: "jobSite:view", mutationPermission: "action-specific", service: "vnext-action-service", mutation: "versioned-action", status: "ACTIVE", testIds: ["idempotency", "action-authorization"] }),
  c({ key: "org-agreement", audience: "ORGANIZATION", navigationSource: "org-job-site-detail", route: "/org/[organizationId]/job-sites/[jobSiteId]", api: "/api/org/[organizationId]/job-sites/[jobSiteId]/agreement", readPermission: "jobSite:view", mutationPermission: "jobSite:update", service: "vnext-job-site-service", mutation: "INITIAL_AGREEMENT_PUBLISH@1", status: "ACTIVE", testIds: ["initial-agreement"] }),
  c({ key: "org-client-invitations", audience: "ORGANIZATION", navigationSource: "org-job-site-detail", route: "/org/[organizationId]/job-sites/[jobSiteId]", api: "/api/org/[organizationId]/job-sites/[jobSiteId]/client-invitations", readPermission: "jobSite:view", mutationPermission: "jobSite:participants:manage", service: "vnext-job-site-service", mutation: "client-invitation-lifecycle", status: "ACTIVE", testIds: ["invite-expiry-replay"] }),
  c({ key: "org-client-participation", audience: "ORGANIZATION", navigationSource: "org-job-site-detail", route: "/org/[organizationId]/job-sites/[jobSiteId]", api: "/api/org/[organizationId]/job-sites/[jobSiteId]/client-participation", readPermission: "jobSite:view", mutationPermission: "jobSite:participants:manage", service: "vnext-job-site-service", mutation: "client-participation-lifecycle", status: "ACTIVE", testIds: ["participant-revocation"] }),
  c({ key: "org-collaborator-invitations", audience: "ORGANIZATION", navigationSource: "org-job-site-detail", route: "/org/[organizationId]/job-sites/[jobSiteId]", api: "/api/org/[organizationId]/job-sites/[jobSiteId]/collaborator-invitations", readPermission: "members:read", mutationPermission: "members:invite", service: "vnext-organization-member-service", mutation: "organization-invitation", status: "ACTIVE", testIds: ["membership-multi-context"] }),
  c({ key: "org-participants", audience: "ORGANIZATION", navigationSource: "org-job-site-detail", route: "/org/[organizationId]/job-sites/[jobSiteId]", api: "/api/org/[organizationId]/job-sites/[jobSiteId]/participants", readPermission: "jobSite:view", mutationPermission: "jobSite:participants:manage", service: "vnext-organization-member-service", mutation: "participant-and-responsible", status: "ACTIVE", testIds: ["participant-isolation"] }),
  c({ key: "org-authority", audience: "ORGANIZATION", navigationSource: "org-job-site-detail", route: "/org/[organizationId]/job-sites/[jobSiteId]", api: "/api/org/[organizationId]/job-sites/[jobSiteId]/authority", readPermission: "jobSite:view", mutationPermission: "OWNER+jobSite:commercial:grant", service: "vnext-collaboration-service", mutation: "authority-grant-revoke", status: "ACTIVE", testIds: ["economic-authority"] }),
  c({ key: "org-timeline", audience: "ORGANIZATION", navigationSource: "org-job-site-detail", route: "/org/[organizationId]/job-sites/[jobSiteId]", api: "/api/org/[organizationId]/job-sites/[jobSiteId]/timeline", readPermission: "jobSite:view", mutationPermission: "jobSite:publish", service: "vnext-collaboration-service", mutation: "TIMELINE_APPEND@1", status: "ACTIVE", testIds: ["timeline-audience"] }),
  c({ key: "org-search", audience: "ORGANIZATION", navigationSource: "org-job-site-detail", route: "/org/[organizationId]/job-sites/[jobSiteId]", api: "/api/org/[organizationId]/job-sites/[jobSiteId]/search", readPermission: "jobSite:view", mutationPermission: null, service: "vnext-collaboration-service", mutation: null, status: "ACTIVE", testIds: ["organization-search-isolation"] }),
  c({ key: "org-steps", audience: "ORGANIZATION", navigationSource: "org-job-site-detail", route: "/org/[organizationId]/job-sites/[jobSiteId]", api: "/api/org/[organizationId]/job-sites/[jobSiteId]/steps", readPermission: "jobSite:view", mutationPermission: "jobSite:steps:manage", service: "vnext-collaboration-service", mutation: "STEP_CREATE@1", status: "ACTIVE", testIds: ["step-lifecycle"] }),
  c({ key: "org-requests", audience: "ORGANIZATION", navigationSource: "org-job-site-detail", route: "/org/[organizationId]/job-sites/[jobSiteId]", api: "/api/org/[organizationId]/job-sites/[jobSiteId]/requests", readPermission: "jobSite:view", mutationPermission: "jobSite:requests:create", service: "vnext-collaboration-service", mutation: "request-lifecycle", status: "ACTIVE", testIds: ["request-lifecycle"] }),
  c({ key: "org-request-transition", audience: "ORGANIZATION", navigationSource: "org-job-site-detail", route: "/org/[organizationId]/job-sites/[jobSiteId]", api: "/api/org/[organizationId]/job-sites/[jobSiteId]/requests/[requestId]", readPermission: "jobSite:view", mutationPermission: "jobSite:requests:respond", service: "vnext-collaboration-service", mutation: "request-transition", status: "ACTIVE", testIds: ["request-lifecycle"] }),
  c({ key: "org-proposals", audience: "ORGANIZATION", navigationSource: "org-job-site-detail", route: "/org/[organizationId]/job-sites/[jobSiteId]", api: "/api/org/[organizationId]/job-sites/[jobSiteId]/proposals", readPermission: "jobSite:view", mutationPermission: "explicit-authority", service: "vnext-collaboration-service", mutation: "proposal-create", status: "ACTIVE", testIds: ["proposal-versioning"] }),
  c({ key: "org-proposal-transition", audience: "ORGANIZATION", navigationSource: "org-job-site-detail", route: "/org/[organizationId]/job-sites/[jobSiteId]", api: "/api/org/[organizationId]/job-sites/[jobSiteId]/proposals/[proposalId]", readPermission: "jobSite:view", mutationPermission: "explicit-authority", service: "vnext-collaboration-service", mutation: "proposal-counter-withdraw", status: "ACTIVE", testIds: ["proposal-stale-rejection"] }),
  c({ key: "org-disputes", audience: "ORGANIZATION", navigationSource: "org-job-site-detail", route: "/org/[organizationId]/job-sites/[jobSiteId]", api: "/api/org/[organizationId]/job-sites/[jobSiteId]/disputes", readPermission: "jobSite:view", mutationPermission: "jobSite:disputes:create", service: "vnext-collaboration-service", mutation: "dispute-create", status: "ACTIVE", testIds: ["dispute-preservation"] }),
  c({ key: "org-dispute-transition", audience: "ORGANIZATION", navigationSource: "org-job-site-detail", route: "/org/[organizationId]/job-sites/[jobSiteId]", api: "/api/org/[organizationId]/job-sites/[jobSiteId]/disputes/[disputeId]", readPermission: "jobSite:view", mutationPermission: "jobSite:disputes:respond", service: "vnext-collaboration-service", mutation: "dispute-transition", status: "ACTIVE", testIds: ["dispute-mutual-resolution"] }),
  c({ key: "org-attachments", audience: "ORGANIZATION", navigationSource: "org-job-site-detail", route: "/org/[organizationId]/job-sites/[jobSiteId]", api: "/api/org/[organizationId]/job-sites/[jobSiteId]/attachments", readPermission: "jobSite:view", mutationPermission: "jobSite:update", service: "vnext-attachment-service", mutation: "ATTACHMENT_UPLOAD@1", status: "ACTIVE", testIds: ["attachment-visibility"] }),
  c({ key: "org-attachment-download", audience: "ORGANIZATION", navigationSource: "org-job-site-detail", route: "/org/[organizationId]/job-sites/[jobSiteId]", api: "/api/org/[organizationId]/job-sites/[jobSiteId]/attachments/[attachmentId]/download", readPermission: "jobSite:view", mutationPermission: null, service: "vnext-attachment-service", mutation: null, status: "ACTIVE", testIds: ["download-audit"] }),
  c({ key: "org-closure", audience: "ORGANIZATION", navigationSource: "org-job-site-detail", route: "/org/[organizationId]/job-sites/[jobSiteId]", api: "/api/org/[organizationId]/job-sites/[jobSiteId]/closure", readPermission: "jobSite:view", mutationPermission: "explicit-closure-authority", service: "vnext-collaboration-service", mutation: "CLOSURE_PROPOSE@1", status: "ACTIVE", testIds: ["closure-stale"] }),
  c({ key: "org-post-closure", audience: "ORGANIZATION", navigationSource: "org-job-site-detail", route: "/org/[organizationId]/job-sites/[jobSiteId]", api: "/api/org/[organizationId]/job-sites/[jobSiteId]/post-closure", readPermission: "jobSite:view", mutationPermission: "jobSite:requests:create", service: "vnext-collaboration-service", mutation: "post-closure-create", status: "ACTIVE", testIds: ["post-closure-append-only"] }),
  c({ key: "org-post-closure-transition", audience: "ORGANIZATION", navigationSource: "org-job-site-detail", route: "/org/[organizationId]/job-sites/[jobSiteId]", api: "/api/org/[organizationId]/job-sites/[jobSiteId]/post-closure/[requestId]", readPermission: "jobSite:view", mutationPermission: "jobSite:requests:respond", service: "vnext-collaboration-service", mutation: "post-closure-transition", status: "ACTIVE", testIds: ["post-closure-append-only"] }),
  c({ key: "org-reopening", audience: "ORGANIZATION", navigationSource: "org-job-site-detail", route: "/org/[organizationId]/job-sites/[jobSiteId]", api: "/api/org/[organizationId]/job-sites/[jobSiteId]/reopening", readPermission: "jobSite:view", mutationPermission: "jobSite:closure:propose", service: "vnext-collaboration-service", mutation: "REOPENING_PROPOSE@1", status: "ACTIVE", testIds: ["reopening-mutual-consent"] }),
  c({ key: "org-legal-holds", audience: "ORGANIZATION", navigationSource: "org-job-site-detail", route: "/org/[organizationId]/job-sites/[jobSiteId]", api: "/api/org/[organizationId]/job-sites/[jobSiteId]/legal-holds", readPermission: "jobSite:view", mutationPermission: "OWNER", service: "vnext-legal-hold-service", mutation: "legal-hold-place-release", status: "ACTIVE", testIds: ["legal-hold-cleanup"] }),
  c({ key: "client-home", audience: "CLIENT", navigationSource: "contexts", route: "/client", api: "/api/client/job-sites", readPermission: "participant", mutationPermission: null, service: "vnext-job-site-service", mutation: null, status: "ACTIVE", testIds: ["client-home-isolation"] }),
  c({ key: "client-data-export", audience: "CLIENT", navigationSource: "client-home", route: "/client", api: "/api/client/data-export", readPermission: "user-scoped", mutationPermission: null, service: "vnext-client-data-export-service", mutation: null, status: "ACTIVE", testIds: ["client-portability"] }),
  c({ key: "client-properties", audience: "CLIENT", navigationSource: "client-home", route: "/client", api: "/api/client/properties", readPermission: "user-scoped", mutationPermission: "user-scoped", service: "vnext-job-site-service", mutation: "client-property-create", status: "ACTIVE", testIds: ["property-cross-company-isolation"] }),
  c({ key: "client-property-link", audience: "CLIENT", navigationSource: "client-home", route: "/client", api: "/api/client/properties/[propertyId]/job-sites", readPermission: "user-scoped", mutationPermission: "user-scoped", service: "vnext-job-site-service", mutation: "client-property-link", status: "ACTIVE", testIds: ["property-cross-company-isolation"] }),
  c({ key: "client-invitation-accept", audience: "CLIENT", navigationSource: "email-token", route: "/client/invitations/[token]", api: "/api/client/invitations/[token]/accept", readPermission: "token+identity", mutationPermission: "verified-email", service: "vnext-job-site-service", mutation: "invitation-accept", status: "ACTIVE", testIds: ["invite-replay"] }),
  c({ key: "client-job-site", audience: "CLIENT", navigationSource: "client-home", route: "/client/job-sites/[jobSiteId]", api: "/api/client/job-sites/[jobSiteId]", readPermission: "participant", mutationPermission: null, service: "vnext-job-site-service", mutation: null, status: "ACTIVE", testIds: ["client-job-site-isolation"] }),
  c({ key: "client-actions", audience: "CLIENT", navigationSource: "client-job-site", route: "/client/job-sites/[jobSiteId]", api: "/api/client/job-sites/[jobSiteId]/actions", readPermission: "participant", mutationPermission: "action-specific", service: "vnext-action-service", mutation: "versioned-action", status: "ACTIVE", testIds: ["client-action-authorization"] }),
  c({ key: "client-timeline", audience: "CLIENT", navigationSource: "client-job-site", route: "/client/job-sites/[jobSiteId]", api: "/api/client/job-sites/[jobSiteId]/timeline", readPermission: "participant+SHARED", mutationPermission: "participant", service: "vnext-collaboration-service", mutation: "TIMELINE_APPEND@1", status: "ACTIVE", testIds: ["timeline-no-internal-leakage"] }),
  c({ key: "client-search", audience: "CLIENT", navigationSource: "client-job-site", route: "/client/job-sites/[jobSiteId]", api: "/api/client/job-sites/[jobSiteId]/search", readPermission: "participant+SHARED", mutationPermission: null, service: "vnext-collaboration-service", mutation: null, status: "ACTIVE", testIds: ["search-no-leakage"] }),
  ...["requests", "requests/[requestId]", "proposals", "proposals/[proposalId]", "disputes", "disputes/[disputeId]", "post-closure", "post-closure/[requestId]", "reopening", "attachments", "attachments/[attachmentId]/download"].map((suffix) => c({ key: `client-${suffix.replace(/\//g, "-").replace(/[\[\]]/g, "")}`, audience: "CLIENT", navigationSource: "client-job-site", route: "/client/job-sites/[jobSiteId]", api: `/api/client/job-sites/[jobSiteId]/${suffix}`, readPermission: "participant", mutationPermission: suffix.endsWith("download") ? null : "lifecycle-specific", service: suffix.startsWith("attachments") ? "vnext-attachment-service" : "vnext-collaboration-service", mutation: suffix.endsWith("download") ? null : "versioned-lifecycle", status: "ACTIVE", testIds: ["client-participant-isolation"] })),
  c({ key: "export-access", audience: "SHARED_AUTHENTICATED", navigationSource: "authenticated-email-link", route: "/exports/access/[token]", api: "/api/exports/access/[token]", readPermission: "token+identity+audience", mutationPermission: "grant-exchange", service: "vnext-export-service", mutation: "export-grant-exchange", status: "ACTIVE", testIds: ["export-token-isolation"] }),
  c({ key: "export-download", audience: "SHARED_AUTHENTICATED", navigationSource: "export-access", route: "/exports/access/[token]", api: "/api/exports/download/[grant]", readPermission: "hashed-grant+identity", mutationPermission: null, service: "vnext-export-service", mutation: null, status: "ACTIVE", testIds: ["export-grant-expiry"] }),
  c({ key: "attachment-finalize", audience: "INTERNAL", navigationSource: null, route: null, api: "/api/internal/vnext/attachments/finalize", readPermission: "INTERNAL_ONLY", mutationPermission: "cron-secret", service: "vnext-action-service", mutation: "ATTACHMENT_FINALIZE@1", status: "INTERNAL_ONLY", testIds: ["attachment-finalize"] }),
  c({ key: "process-runner", audience: "INTERNAL", navigationSource: null, route: null, api: "/api/internal/vnext/processes/run", readPermission: "INTERNAL_ONLY", mutationPermission: "cron-secret", service: "vnext-process-service", mutation: "process-claim-run", status: "INTERNAL_ONLY", testIds: ["process-claim-fencing"] }),
] as const;

export function assertVNextRegistry() {
  if (VNEXT_ACTION_DEFINITIONS.some((action) => action.includes("GENERIC_UPDATE"))) throw new Error("GENERIC_UPDATE is forbidden.");
  if (new Set(VNEXT_ACTION_DEFINITIONS).size !== VNEXT_ACTION_DEFINITIONS.length) throw new Error("Duplicate vNext action definition.");
  if (Object.keys(VNEXT_PROCESS_DEFINITIONS).length !== 8) throw new Error("The canonical vNext process registry must contain eight processes.");
  const capabilities = PRODUCT_CAPABILITY_MANIFEST as ReadonlyArray<ProductCapability>;
  if (new Set(capabilities.map((capability) => capability.key)).size !== capabilities.length) throw new Error("Duplicate product capability key.");
  for (const capability of capabilities) {
    if (!capability.service || !capability.api || !capability.testIds.length) throw new Error(`Incomplete capability ${capability.key}.`);
    if (capability.status === "ACTIVE" && (!capability.route || !capability.navigationSource)) throw new Error(`Active capability ${capability.key} is not reachable.`);
    if (capability.status === "INTERNAL_ONLY" && (capability.route || capability.navigationSource)) throw new Error(`Internal capability ${capability.key} is navigable.`);
  }
  return true;
}
