"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { IconArrowLeft, IconArrowRight, IconCheck, IconInfoCircle } from "@tabler/icons-react";
import { Alert, AlertDescription, AlertTitle } from "@qoovex/ui/components/alert";
import { Button } from "@qoovex/ui/components/button";
import { Field, FieldDescription, FieldError, FieldGroup, FieldLabel } from "@qoovex/ui/components/field";
import { Input } from "@qoovex/ui/components/input";
import { Textarea } from "@qoovex/ui/components/textarea";
import { jobSiteOperationalPhaseLabels, jobSiteOperationalPhases } from "@qoovex/types";
import type { JobSiteOperationalPhase } from "@qoovex/types";
import { submitJson } from "../admin-api-client";
import type { WorkspaceJobSiteRecord } from "@/views/workspace/workspace-records";

type AssignmentOptions = { workers: Array<{ id: string; displayName: string; roleLabel?: string | null }>; users: Array<{ id: string; label: string; email: string; role: string }> };
type Draft = { name: string; clientName: string; address: string; operationalPhase: JobSiteOperationalPhase; scheduleNow: boolean; startDate: string; endDate: string; managerUserIds: string[]; workerIds: string[]; peopleLater: boolean; nextStep: "overview" | "documents" | "people" | "activities"; notes: string };
const stepLabels = ["Identita", "Fase e periodo", "Persone", "Prossimo passo", "Riepilogo"];
const initialDraft: Draft = { name: "", clientName: "", address: "", operationalPhase: "PREPARATION", scheduleNow: false, startDate: "", endDate: "", managerUserIds: [], workerIds: [], peopleLater: false, nextStep: "overview", notes: "" };
function toggle(values: string[], value: string) { return values.includes(value) ? values.filter((item) => item !== value) : [...values, value]; }

export function JobSiteCreateWizard({ onCreated }: { onCreated?: (jobSite: WorkspaceJobSiteRecord) => void }) {
  const router = useRouter();
  const [step, setStep] = useState(0);
  const [draft, setDraft] = useState(initialDraft);
  const [options, setOptions] = useState<AssignmentOptions>({ workers: [], users: [] });
  const [pending, setPending] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [duplicates, setDuplicates] = useState<Array<{ id: string; name: string; clientName?: string | null }>>([]);
  const managers = useMemo(() => options.users.filter((item) => item.role === "SITE_MANAGER"), [options.users]);

  useEffect(() => { let active = true; fetch("/api/resource-assignments/options", { headers: { accept: "application/json" } }).then(async (response) => response.ok ? response.json() : Promise.reject(new Error())).then((payload: AssignmentOptions) => { if (active) setOptions(payload); }).catch(() => undefined); return () => { active = false; }; }, []);
  function validateCurrentStep() { if (step === 0 && draft.name.trim().length < 2) return "Inserisci il nome del cantiere."; if (step === 1 && draft.scheduleNow && (!draft.startDate || !draft.endDate)) return "Inserisci entrambe le date oppure scegli di pianificarle dopo."; if (step === 1 && draft.scheduleNow && draft.endDate < draft.startDate) return "La data fine non puo precedere la data inizio."; if (step === 2 && !draft.peopleLater && !draft.managerUserIds.length && !draft.workerIds.length) return "Seleziona almeno una persona oppure conferma che assegnerai le persone dopo."; return null; }
  function next() { const message = validateCurrentStep(); if (message) { setError(message); return; } setError(null); setStep((current) => Math.min(4, current + 1)); }
  async function create(continueAfterDuplicateWarning = false) { setPending(true); setError(null); try { if (!continueAfterDuplicateWarning) { const result = await submitJson<{ matches: typeof duplicates }>("/api/job-sites/duplicate-check", "POST", { name: draft.name, clientName: draft.clientName || null, address: draft.address || null }); if (result.matches.length) { setDuplicates(result.matches); setPending(false); return; } } const created = await submitJson<WorkspaceJobSiteRecord>("/api/job-sites", "POST", { name: draft.name, clientName: draft.clientName || null, address: draft.address || null, operationalPhase: draft.operationalPhase, startDate: draft.scheduleNow ? draft.startDate : null, endDate: draft.scheduleNow ? draft.endDate : null, managerUserIds: draft.managerUserIds, workerIds: draft.workerIds, notes: draft.notes || null, continueAfterDuplicateWarning }); onCreated?.(created); router.refresh(); router.push(`/job-sites/${created.id}?section=${draft.nextStep}`); } catch (submitError) { setError(submitError instanceof Error ? submitError.message : "Creazione non riuscita."); } finally { setPending(false); } }

  return <div className="grid gap-5">
    <ol aria-label="Avanzamento creazione" className="grid grid-cols-5 gap-1">{stepLabels.map((label, index) => <li aria-current={index === step ? "step" : undefined} className="min-w-0" key={label}><span className={`block h-1.5 rounded-full ${index <= step ? "bg-primary" : "bg-muted"}`} /><span className="mt-1 hidden truncate text-[11px] text-muted-foreground sm:block">{index + 1}. {label}</span></li>)}</ol>
    {error ? <FieldError>{error}</FieldError> : null}
    {step === 0 ? <FieldGroup className="gap-4"><div><h3 className="font-medium">Identita del cantiere</h3><p className="mt-1 text-sm text-muted-foreground">Registra solo le informazioni operative necessarie.</p></div><Field><FieldLabel htmlFor="wizard-job-site-name">Nome cantiere</FieldLabel><Input autoFocus id="wizard-job-site-name" maxLength={160} minLength={2} onChange={(event) => setDraft({ ...draft, name: event.target.value })} required value={draft.name} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field><FieldLabel htmlFor="wizard-job-site-client">Committente</FieldLabel><Input id="wizard-job-site-client" maxLength={160} onChange={(event) => setDraft({ ...draft, clientName: event.target.value })} value={draft.clientName} /></Field><Field><FieldLabel htmlFor="wizard-job-site-address">Indirizzo</FieldLabel><Input autoComplete="street-address" id="wizard-job-site-address" maxLength={500} onChange={(event) => setDraft({ ...draft, address: event.target.value })} value={draft.address} /></Field></div></FieldGroup> : null}
    {step === 1 ? <FieldGroup className="gap-4"><div><h3 className="font-medium">Fase e periodo</h3><p className="mt-1 text-sm text-muted-foreground">La fase e obbligatoria e non viene dedotta dalle date.</p></div><Field><FieldLabel htmlFor="wizard-job-site-phase">Fase operativa</FieldLabel><select className="h-10 rounded-md border bg-background px-3 text-sm" id="wizard-job-site-phase" onChange={(event) => setDraft({ ...draft, operationalPhase: event.target.value as JobSiteOperationalPhase })} value={draft.operationalPhase}>{jobSiteOperationalPhases.map((phase) => <option key={phase} value={phase}>{jobSiteOperationalPhaseLabels[phase]}</option>)}</select></Field><label className="flex items-start gap-3 rounded-lg border p-3 text-sm"><input checked={draft.scheduleNow} className="mt-0.5 size-4" onChange={(event) => setDraft({ ...draft, scheduleNow: event.target.checked })} type="checkbox" /><span><strong className="block font-medium">Definisci ora il periodo</strong><span className="text-muted-foreground">Lascia disattivato per pianificare le date in seguito.</span></span></label>{draft.scheduleNow ? <div className="grid gap-4 sm:grid-cols-2"><Field><FieldLabel htmlFor="wizard-start-date">Data inizio</FieldLabel><Input id="wizard-start-date" onChange={(event) => setDraft({ ...draft, startDate: event.target.value })} required type="date" value={draft.startDate} /></Field><Field><FieldLabel htmlFor="wizard-end-date">Data fine</FieldLabel><Input id="wizard-end-date" onChange={(event) => setDraft({ ...draft, endDate: event.target.value })} required type="date" value={draft.endDate} /></Field></div> : null}</FieldGroup> : null}
    {step === 2 ? <FieldGroup className="gap-4"><div><h3 className="font-medium">Persone</h3><p className="mt-1 text-sm text-muted-foreground">Le responsabilita restano relazioni operative separate dal profilo del cantiere.</p></div><div className="grid gap-4 sm:grid-cols-2"><fieldset className="rounded-lg border p-3"><legend className="px-1 text-sm font-medium">Responsabili cantiere</legend><div className="mt-2 grid max-h-40 gap-2 overflow-y-auto">{managers.length ? managers.map((item) => <label className="flex items-start gap-2 text-sm" key={item.id}><input checked={draft.managerUserIds.includes(item.id)} className="mt-0.5 size-4" onChange={() => setDraft({ ...draft, managerUserIds: toggle(draft.managerUserIds, item.id), peopleLater: false })} type="checkbox" /><span>{item.label}<span className="block text-xs text-muted-foreground">{item.email}</span></span></label>) : <p className="text-sm text-muted-foreground">Nessun account SITE_MANAGER disponibile.</p>}</div></fieldset><fieldset className="rounded-lg border p-3"><legend className="px-1 text-sm font-medium">Lavoratori</legend><div className="mt-2 grid max-h-40 gap-2 overflow-y-auto">{options.workers.length ? options.workers.map((item) => <label className="flex items-start gap-2 text-sm" key={item.id}><input checked={draft.workerIds.includes(item.id)} className="mt-0.5 size-4" onChange={() => setDraft({ ...draft, workerIds: toggle(draft.workerIds, item.id), peopleLater: false })} type="checkbox" /><span>{item.displayName}<span className="block text-xs text-muted-foreground">{item.roleLabel || "Mansione non indicata"}</span></span></label>) : <p className="text-sm text-muted-foreground">Nessun lavoratore disponibile.</p>}</div></fieldset></div><label className="flex items-start gap-3 rounded-lg bg-muted/50 p-3 text-sm"><input checked={draft.peopleLater} className="mt-0.5 size-4" onChange={(event) => setDraft({ ...draft, peopleLater: event.target.checked, managerUserIds: event.target.checked ? [] : draft.managerUserIds, workerIds: event.target.checked ? [] : draft.workerIds })} type="checkbox" /><span><strong className="block font-medium">Assegnero le persone dopo</strong><span className="text-muted-foreground">Il cantiere verra segnalato nella coda di attenzione.</span></span></label></FieldGroup> : null}
    {step === 3 ? <FieldGroup className="gap-4"><div><h3 className="font-medium">Scegli il prossimo passo</h3><p className="mt-1 text-sm text-muted-foreground">Qoovex aprira la sezione scelta, senza creare automaticamente documenti, checklist o scadenze.</p></div><div className="grid gap-2 sm:grid-cols-2">{([['overview','Apri il riepilogo'],['documents','Aggiungi documenti'],['people','Verifica le persone'],['activities','Pianifica attivita']] as const).map(([value, label]) => <label className={`rounded-lg border p-3 text-sm ${draft.nextStep === value ? "border-primary bg-primary/5" : ""}`} key={value}><input checked={draft.nextStep === value} className="mr-2 size-4 align-middle" name="nextStep" onChange={() => setDraft({ ...draft, nextStep: value })} type="radio" />{label}</label>)}</div><Field><FieldLabel htmlFor="wizard-job-site-notes">Note operative non sensibili</FieldLabel><Textarea id="wizard-job-site-notes" maxLength={4000} onChange={(event) => setDraft({ ...draft, notes: event.target.value })} rows={3} value={draft.notes} /><FieldDescription>Non inserire dati sanitari, fiscali, coordinate o segreti.</FieldDescription></Field></FieldGroup> : null}
    {step === 4 ? <div className="grid gap-4"><div><h3 className="font-medium">Riepilogo</h3><p className="mt-1 text-sm text-muted-foreground">Controlla prima della creazione atomica.</p></div><dl className="grid gap-3 rounded-lg bg-muted/50 p-4 text-sm sm:grid-cols-2"><div><dt className="text-muted-foreground">Cantiere</dt><dd className="font-medium">{draft.name}</dd></div><div><dt className="text-muted-foreground">Fase</dt><dd className="font-medium">{jobSiteOperationalPhaseLabels[draft.operationalPhase]}</dd></div><div><dt className="text-muted-foreground">Periodo</dt><dd className="font-medium">{draft.scheduleNow ? `${draft.startDate} - ${draft.endDate}` : "Da pianificare"}</dd></div><div><dt className="text-muted-foreground">Persone</dt><dd className="font-medium">{draft.managerUserIds.length} responsabili · {draft.workerIds.length} lavoratori</dd></div></dl>{duplicates.length ? <Alert variant="warning"><IconInfoCircle aria-hidden="true" /><AlertTitle>Possibile duplicato</AlertTitle><AlertDescription><p>Esistono cantieri con nome, committente o indirizzo corrispondente:</p><ul className="mt-2 list-disc pl-5">{duplicates.map((item) => <li key={item.id}>{item.name}{item.clientName ? ` · ${item.clientName}` : ""}</li>)}</ul><Button className="mt-3" disabled={pending} onClick={() => void create(true)} size="sm" type="button" variant="outline">Conferma e crea comunque</Button></AlertDescription></Alert> : null}</div> : null}
    <div className="flex flex-col-reverse gap-2 border-t pt-4 sm:flex-row sm:justify-between"><Button disabled={pending || step === 0} onClick={() => { setError(null); setDuplicates([]); setStep((current) => Math.max(0, current - 1)); }} type="button" variant="outline"><IconArrowLeft aria-hidden="true" />Indietro</Button>{step < 4 ? <Button disabled={pending} onClick={next} type="button">Continua<IconArrowRight aria-hidden="true" /></Button> : <Button disabled={pending || duplicates.length > 0} onClick={() => void create(false)} type="button"><IconCheck aria-hidden="true" />{pending ? "Creazione..." : "Crea cantiere"}</Button>}</div>
  </div>;
}
