import Link from "next/link";
import { IconAlertTriangle, IconArrowUpRight, IconBuilding, IconHistory, IconProgress } from "@tabler/icons-react";
import { Badge } from "@qoovex/ui/components/badge";
import { buttonVariants } from "@qoovex/ui/components/button";
import { Card, CardAction, CardContent, CardDescription, CardHeader, CardTitle } from "@qoovex/ui/components/card";
import { cn } from "@qoovex/ui/lib/utils";
import { jobSiteOperationalPhaseLabels, legacyJobSiteOperationalPhaseLabel } from "@qoovex/types";
import type { JobSiteOverviewResponse } from "@qoovex/types";
import { JobSiteCreateDialog } from "./JobSiteCreateDialog";
import { WorkspacePage, WorkspacePageHeader, WorkspaceState } from "@/views/workspace/WorkspacePrimitives";
import type { WorkspaceCapabilities } from "@/views/workspace/workspace-records";

const phaseOrder = ["DRAFT", "PREPARATION", "IN_PROGRESS", "PAUSED", "CLOSING", "COMPLETED", "UNSET"] as const;

export function JobSitesOverviewView({ overview, capabilities, initialCreateOpen = false }: { overview: JobSiteOverviewResponse; capabilities: WorkspaceCapabilities; initialCreateOpen?: boolean }) {
  return <WorkspacePage>
    <WorkspacePageHeader title="Cantieri" description="Una vista decisionale su fase, criticita operative e attivita recente dei cantieri accessibili." action={capabilities.canCreateJobSites ? <JobSiteCreateDialog className="h-10 w-full sm:h-8 sm:w-auto" initialOpen={initialCreateOpen} /> : undefined} />
    <section aria-labelledby="job-site-phases"><div className="mb-3 flex items-center justify-between gap-3"><div><h2 className="text-lg font-semibold" id="job-site-phases">Fasi operative</h2><p className="text-sm text-muted-foreground">La fase e dichiarata, mai dedotta dalle date.</p></div><Link className={buttonVariants({ size: "sm", variant: "outline" })} href="/job-sites/all">Elenco completo<IconArrowUpRight aria-hidden="true" /></Link></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-7">{phaseOrder.map((phase) => <Card key={phase} size="sm"><CardContent className="p-4"><div className="flex items-center justify-between gap-2"><IconProgress aria-hidden="true" className="size-4 text-muted-foreground" /><strong className="text-2xl tabular-nums">{overview.phaseCounts[phase]}</strong></div><p className="mt-3 text-sm font-medium">{phase === "UNSET" ? legacyJobSiteOperationalPhaseLabel : jobSiteOperationalPhaseLabels[phase]}</p></CardContent></Card>)}</div></section>
    <div className="grid min-w-0 gap-6 xl:grid-cols-[minmax(0,1.45fr)_minmax(19rem,0.8fr)]">
      <Card className="min-w-0" size="sm"><CardHeader className="border-b"><CardTitle><h2>Coda di attenzione</h2></CardTitle><CardDescription>Ordine deterministico: scadenze e documenti critici, completezza delle assegnazioni, poi attivita aperte.</CardDescription><CardAction><Badge variant="outline"><IconAlertTriangle aria-hidden="true" />{overview.attentionQueue.length}</Badge></CardAction></CardHeader><CardContent>{overview.attentionQueue.length ? <ol className="divide-y divide-border">{overview.attentionQueue.map((item, index) => <li className="grid gap-3 py-4 first:pt-0 last:pb-0 sm:grid-cols-[auto_minmax(0,1fr)_auto] sm:items-center" key={item.id}><span className="grid size-8 place-items-center rounded-full bg-muted text-sm font-semibold tabular-nums">{index + 1}</span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><strong className="[overflow-wrap:anywhere] text-sm">{item.name}</strong><WorkspaceState label={item.operationalPhase ? jobSiteOperationalPhaseLabels[item.operationalPhase] : legacyJobSiteOperationalPhaseLabel} tone="info" /></div><p className="mt-1 text-xs text-muted-foreground">{item.summary.overdueDeadlines} scadenze superate · {item.summary.missingDocuments + item.summary.expiredDocuments + item.summary.documentsToReview} documenti da gestire · {item.summary.openChecklistItems + item.summary.checklistItemsToReview} voci checklist</p></div><Link className={buttonVariants({ size: "sm", variant: "outline" })} href={`/job-sites/${item.id}`}>Apri</Link></li>)}</ol> : <div className="rounded-lg border border-dashed p-8 text-center"><IconBuilding aria-hidden="true" className="mx-auto size-6 text-muted-foreground" /><p className="mt-3 font-medium">Nessuna attenzione rilevata</p><p className="mt-1 text-sm text-muted-foreground">I dati correnti non producono segnali operativi.</p></div>}</CardContent></Card>
      <Card className="min-w-0" size="sm"><CardHeader className="border-b"><CardTitle><h2>Attivita recente</h2></CardTitle><CardDescription>Aggiornamenti reali da documenti, checklist, prove e pacchetti.</CardDescription><CardAction><IconHistory aria-hidden="true" className="size-4 text-muted-foreground" /></CardAction></CardHeader><CardContent>{overview.recentActivity.length ? <ul className="grid gap-2">{overview.recentActivity.map((item) => <li key={`${item.kind}-${item.id}`}><Link className="block rounded-lg border p-3 transition-colors hover:bg-muted/50" href={item.href}><span className="block text-xs font-medium text-muted-foreground">{item.jobSiteName}</span><strong className="mt-1 block [overflow-wrap:anywhere] text-sm">{item.label}</strong><span className="mt-1 block text-xs text-muted-foreground">{new Intl.DateTimeFormat("it-IT", { dateStyle: "medium" }).format(new Date(item.updatedAt))}</span></Link></li>)}</ul> : <p className="text-sm text-muted-foreground">Nessuna attivita recente disponibile.</p>}</CardContent></Card>
    </div>
  </WorkspacePage>;
}
