import Link from "next/link";
import { IconArrowLeft, IconCalendarDue, IconChecklist, IconDownload, IconFileDescription, IconPackageExport, IconPhoto, IconSettings, IconUserCheck, IconUsers } from "@tabler/icons-react";
import { Badge } from "@qoovex/ui/components/badge";
import { buttonVariants } from "@qoovex/ui/components/button";
import { Card, CardAction, CardContent, CardDescription, CardHeader, CardTitle } from "@qoovex/ui/components/card";
import { cn } from "@qoovex/ui/lib/utils";
import { jobSiteOperationalPhaseLabels, legacyJobSiteOperationalPhaseLabel } from "@qoovex/types";
import type { JobSiteDetailSection, JobSiteOperationalListItem, JobSiteUserAssignmentResponse, JobSiteWorkerAssignmentResponse, MissingDocumentRequirementItem } from "@qoovex/types";
import { DocumentCategoryList } from "@/views/admin-core/documents/DocumentCategoryList";
import { DashboardAssignmentDialog } from "@/views/dashboard/DashboardAssignmentDialog";
import { WorkspacePageIdentity } from "@/views/workspace/WorkspacePageIdentity";
import { WorkspacePage, WorkspacePageHeader, WorkspaceState } from "@/views/workspace/WorkspacePrimitives";
import { deadlineStatusLabels, evidenceTypeLabels, formatDate, statusTone } from "@/views/workspace/workspace-format";
import type { WorkspaceCapabilities, WorkspaceChecklistRecord, WorkspaceDeadlineRecord, WorkspaceDocumentPackageRecord, WorkspaceDocumentRecord, WorkspaceEvidenceRecord } from "@/views/workspace/workspace-records";
import { JobSiteArchiveButton } from "./JobSiteArchiveButton";
import { JobSiteForm } from "./JobSiteForm";
import { JobSiteQuickActions } from "./JobSiteQuickActions";
import { OperationalArtifactStatus } from "@entities/operational-process/ui/OperationalArtifactStatus";

const sections: Array<{ id: JobSiteDetailSection; label: string }> = [
  { id: "overview", label: "Riepilogo" }, { id: "documents", label: "Documenti" }, { id: "people", label: "Persone" },
  { id: "activities", label: "Attivita e scadenze" }, { id: "evidence", label: "Prove" }, { id: "sharing", label: "Condivisioni" }, { id: "settings", label: "Impostazioni" },
];

function EmptySection({ children }: { children: string }) { return <div className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">{children}</div>; }

export function JobSiteDetailSegmentedView({ jobSite, section, capabilities, documents = [], missingDocuments = [], deadlines = [], checklists = [], evidence = [], packages = [], userAssignments = [], workerAssignments = [], returnToDashboard = false }: {
  jobSite: JobSiteOperationalListItem; section: JobSiteDetailSection; capabilities: WorkspaceCapabilities; documents?: WorkspaceDocumentRecord[]; missingDocuments?: MissingDocumentRequirementItem[]; deadlines?: WorkspaceDeadlineRecord[]; checklists?: WorkspaceChecklistRecord[]; evidence?: WorkspaceEvidenceRecord[]; packages?: WorkspaceDocumentPackageRecord[]; userAssignments?: JobSiteUserAssignmentResponse[]; workerAssignments?: JobSiteWorkerAssignmentResponse[]; returnToDashboard?: boolean;
}) {
  const record = jobSite;
  const managerLabel = userAssignments.length ? userAssignments.map((item) => item.userLabel).join(", ") : "Non assegnato";
  return <WorkspacePage>
    <WorkspacePageIdentity label={jobSite.name} />
    <WorkspacePageHeader title={jobSite.name} description={jobSite.clientName || "Committente non indicato"} action={<Link className={cn(buttonVariants({ variant: "outline" }), "h-10 sm:h-8")} href={returnToDashboard ? "/dashboard" : "/job-sites"}><IconArrowLeft aria-hidden="true" />{returnToDashboard ? "Torna al Centro operativo" : "Torna ai cantieri"}</Link>} />
    <OperationalArtifactStatus artifactId={jobSite.id} artifactType="JOB_SITE" />
    <nav aria-label="Sezioni cantiere" className="-mx-1 overflow-x-auto px-1"><div className="flex min-w-max gap-1 rounded-lg border bg-muted/30 p-1">{sections.filter((item) => item.id !== "settings" || capabilities.canManageCore).map((item) => <Link aria-current={section === item.id ? "page" : undefined} className={cn(buttonVariants({ size: "sm", variant: section === item.id ? "default" : "ghost" }), "whitespace-nowrap")} href={`/job-sites/${jobSite.id}?section=${item.id}`} key={item.id}>{item.label}</Link>)}</div></nav>

    {section === "overview" ? <><Card size="sm"><CardHeader className="border-b"><CardTitle><h2>Riepilogo operativo</h2></CardTitle><CardDescription>Fase dichiarata, periodo e segnali sintetici.</CardDescription><CardAction><WorkspaceState label={jobSite.operationalPhase ? jobSiteOperationalPhaseLabels[jobSite.operationalPhase] : legacyJobSiteOperationalPhaseLabel} tone={jobSite.operationalPhase === "PAUSED" ? "warning" : "info"} /></CardAction></CardHeader><CardContent className="grid gap-5"><dl className="grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><div className="sm:col-span-2"><dt className="text-xs text-muted-foreground">Indirizzo</dt><dd className="mt-1 font-medium">{jobSite.address || "Non registrato"}</dd></div><div><dt className="text-xs text-muted-foreground">Inizio</dt><dd className="mt-1 font-medium">{formatDate(jobSite.startDate)}</dd></div><div><dt className="text-xs text-muted-foreground">Fine</dt><dd className="mt-1 font-medium">{formatDate(jobSite.endDate)}</dd></div></dl><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-lg bg-muted/60 p-3"><span className="text-xs text-muted-foreground">Documenti critici</span><strong className="mt-1 block text-xl">{jobSite.summary.missingDocuments + jobSite.summary.expiredDocuments + jobSite.summary.documentsToReview}</strong></div><div className="rounded-lg bg-muted/60 p-3"><span className="text-xs text-muted-foreground">Voci checklist</span><strong className="mt-1 block text-xl">{jobSite.summary.openChecklistItems + jobSite.summary.checklistItemsToReview}</strong></div><div className="rounded-lg bg-muted/60 p-3"><span className="text-xs text-muted-foreground">Scadenze da gestire</span><strong className="mt-1 block text-xl">{jobSite.summary.overdueDeadlines + jobSite.summary.upcomingDeadlines}</strong></div><div className="rounded-lg bg-muted/60 p-3"><span className="text-xs text-muted-foreground">Persone assegnate</span><strong className="mt-1 block text-xl">{jobSite.summary.managerCount + jobSite.summary.workerCount}</strong></div></div><div className="rounded-lg border p-3"><h3 className="text-sm font-medium">Note operative non sensibili</h3><p className="mt-2 whitespace-pre-wrap text-sm text-muted-foreground">{jobSite.notes || "Nessuna nota operativa registrata."}</p></div></CardContent></Card><Card size="sm"><CardHeader className="border-b"><CardTitle><h2>Azioni operative</h2></CardTitle><CardDescription>Ogni nuovo elemento resta collegato a questo cantiere.</CardDescription></CardHeader><CardContent><JobSiteQuickActions capabilities={capabilities} jobSite={record} /></CardContent></Card></> : null}

    {section === "documents" ? <Card size="sm"><CardHeader className="border-b"><CardTitle><h2>Documenti per categoria</h2></CardTitle><CardDescription>Requisiti configurati e documenti presenti, mancanti o da verificare.</CardDescription><CardAction><Badge variant="outline"><IconFileDescription aria-hidden="true" />{documents.length + missingDocuments.length}</Badge></CardAction></CardHeader><CardContent><DocumentCategoryList documents={documents} missing={missingDocuments} /></CardContent></Card> : null}
    {section === "people" ? <div className="grid gap-6 lg:grid-cols-2"><Card size="sm"><CardHeader className="border-b"><CardTitle><h2>Responsabili cantiere</h2></CardTitle><CardDescription>Account SITE_MANAGER assegnati al contesto.</CardDescription><CardAction><Badge variant="outline"><IconUserCheck aria-hidden="true" />{userAssignments.length}</Badge></CardAction></CardHeader><CardContent className="grid gap-4"><p className="text-sm font-medium">{managerLabel}</p>{capabilities.canManageAssignments ? <DashboardAssignmentDialog contextId={jobSite.id} contextKind="JOB_SITE" contextLabel={jobSite.name} excludedUserIds={userAssignments.map((item) => item.userId)} primaryAction responsibilityLabel={managerLabel} triggerLabel="Aggiungi responsabile cantiere" /> : null}<Link className={buttonVariants({ size: "sm", variant: "outline" })} href={`/people/assignments?jobSiteId=${jobSite.id}`}><IconUsers aria-hidden="true" />Vedi assegnazioni</Link></CardContent></Card><Card size="sm"><CardHeader className="border-b"><CardTitle><h2>Lavoratori assegnati</h2></CardTitle><CardDescription>Profili operativi, separati dagli accessi applicativi.</CardDescription><CardAction><Badge variant="outline"><IconUsers aria-hidden="true" />{workerAssignments.length}</Badge></CardAction></CardHeader><CardContent>{workerAssignments.length ? <ul className="grid gap-2">{workerAssignments.map((item) => <li className="rounded-lg border p-3" key={item.id}><strong className="text-sm">{item.workerDisplayName}</strong><span className="mt-1 block text-xs text-muted-foreground">{item.workerRoleLabel || "Mansione non indicata"}</span></li>)}</ul> : <EmptySection>Nessun lavoratore assegnato.</EmptySection>}</CardContent></Card></div> : null}
    {section === "activities" ? <div className="grid gap-6 lg:grid-cols-2"><Card size="sm"><CardHeader className="border-b"><CardTitle><h2>Scadenze</h2></CardTitle><CardDescription>Date operative collegate.</CardDescription><CardAction><Badge variant="outline"><IconCalendarDue aria-hidden="true" />{deadlines.length}</Badge></CardAction></CardHeader><CardContent>{deadlines.length ? <ul className="grid gap-2">{deadlines.map((item) => <li className="flex items-center justify-between gap-3 rounded-lg border p-3" key={item.id}><div><strong className="text-sm">{item.title}</strong><span className="block text-xs text-muted-foreground">{formatDate(item.dueDate)}</span></div><WorkspaceState label={deadlineStatusLabels[item.status]} tone={statusTone(item.status)} /></li>)}</ul> : <EmptySection>Nessuna scadenza collegata.</EmptySection>}</CardContent></Card><Card size="sm"><CardHeader className="border-b"><CardTitle><h2>Checklist</h2></CardTitle><CardDescription>Attivita verificabili del cantiere.</CardDescription><CardAction><Badge variant="outline"><IconChecklist aria-hidden="true" />{checklists.length}</Badge></CardAction></CardHeader><CardContent>{checklists.length ? <ul className="grid gap-2">{checklists.map((item) => <li className="flex items-center justify-between gap-3 rounded-lg border p-3" key={item.id}><div><strong className="text-sm">{item.name}</strong><span className="block text-xs text-muted-foreground">{item.items?.filter((entry) => entry.status !== "DONE").length ?? 0} voci aperte</span></div><Link className={buttonVariants({ size: "sm", variant: "outline" })} href={`/checklists/${item.id}`}>Apri</Link></li>)}</ul> : <EmptySection>Nessuna checklist collegata.</EmptySection>}</CardContent></Card></div> : null}
    {section === "evidence" ? <Card size="sm"><CardHeader className="border-b"><CardTitle><h2>Prove</h2></CardTitle><CardDescription>Foto, file e note operative. Nessuna chiave Blob e inclusa nel payload.</CardDescription><CardAction><Badge variant="outline"><IconPhoto aria-hidden="true" />{evidence.length}</Badge></CardAction></CardHeader><CardContent>{evidence.length ? <ul className="grid gap-2">{evidence.map((item) => <li className="flex items-center justify-between gap-3 rounded-lg border p-3" key={item.id}><div><strong className="text-sm">{item.title}</strong><span className="block text-xs text-muted-foreground">{evidenceTypeLabels[item.type]}</span></div>{item.hasFile ? <a className={buttonVariants({ size: "sm", variant: "outline" })} href={`/api/evidence/${item.id}/download`}><IconDownload aria-hidden="true" />Scarica</a> : null}</li>)}</ul> : <EmptySection>Nessuna prova collegata.</EmptySection>}</CardContent></Card> : null}
    {section === "sharing" ? <Card size="sm"><CardHeader className="border-b"><CardTitle><h2>Condivisioni</h2></CardTitle><CardDescription>Pacchetti preparati; token e URL permanenti non vengono esposti.</CardDescription><CardAction><Badge variant="outline"><IconPackageExport aria-hidden="true" />{packages.length}</Badge></CardAction></CardHeader><CardContent>{packages.length ? <ul className="grid gap-2">{packages.map((item) => <li className="flex items-center justify-between gap-3 rounded-lg border p-3" key={item.id}><div><strong className="text-sm">{item.title}</strong><span className="block text-xs text-muted-foreground">{item.items?.length ?? 0} elementi</span></div><Link className={buttonVariants({ size: "sm", variant: "outline" })} href={`/document-packages/${item.id}`}>Apri</Link></li>)}</ul> : <EmptySection>Nessuna condivisione preparata.</EmptySection>}</CardContent></Card> : null}
    {section === "settings" && capabilities.canManageCore ? <Card size="sm"><CardHeader className="border-b"><CardTitle><h2><IconSettings aria-hidden="true" className="mr-2 inline size-4" />Impostazioni</h2></CardTitle><CardDescription>Aggiorna fase e informazioni oppure archivia senza eliminare relazioni e file.</CardDescription></CardHeader><CardContent className="grid gap-6"><JobSiteForm jobSite={record} mode="update" /><div className="border-t pt-5"><h3 className="text-sm font-medium text-destructive">Archivia cantiere</h3><p className="my-2 text-sm text-muted-foreground">Il cantiere resta consultabile nell'archivio; non e previsto il ripristino.</p><JobSiteArchiveButton jobSiteId={jobSite.id} redirectToList /></div></CardContent></Card> : null}
  </WorkspacePage>;
}
